### ISSUE TITLE
[Theme] Display the favicons of the result links.

### ISSUE THREAD

**Issue by Nocifer** [searxng/searxng#1014]
**Is your feature request related to a problem? Please describe.**
The one thing I miss in SearxNG is showing a site's favicon next to its link in the results page. It's a tremendously helpful feature when you're quickly scanning the results and trying to determine what's what.

**Describe the solution you'd like**
I'd like it if the site's favicon were displayed next to each result.

**Describe alternatives you've considered**
Instead of making this behavior the default, perhaps a toggle in the settings could be implemented.

**Additional context**
AFAICT, this was briefly discussed in #504 (in the OP: "..._Also, I believe someone proposed adding the website icons next to the results, and in this case, we may add them to the left of the URL like DDG does._") but was seemingly forgotten/fallen out of view as the discussion in that thread shifted to how the links themselves are displayed, which resulted in #510.

**Comment by mrpaulblack** [comment]
Well I did a experimental PR about that here: https://github.com/searxng/searxng/pull/441 (I was just using the google cache for the favicons...)

There was also a discussion somewhere else about this, but I forgot where. Basically the end of the discussion was: It is a great UX feature, but the privacy suffers and/or the stakc gets much more complicated. For example, if we just get the favicons from the sites themself or use the google cache, a lot of domains are going to get pinged by the enduser or by the SearXNG instance (depends on if image proxy is enabled or disabled.) Also this would add a lot more requests to a single result page. We could impl like an extra service that stores favicons and serve them out. But this would make the stack more complicated.

I think what is actually doable in the future is for example add favicons to the video results. Since we only need a few for the different video engines and not more. Maybe we could even expand to the news category in the future future, but for now I think its better if not not impl. this...

**Comment by Nocifer** [comment]
Ah, it seems I completely failed to notice your reply in the #504 thread. So, judging by how #441 went, this is indeed something that the dev team is already very aware of, but that will probably not get much further traction for the time being, if at all, due to the stated reasons.

While I'm not too sure about the privacy issues (because it would be togglable and disabled by default, so it would just be one more tool for the user/host to judge its merit and decide whether to use it or not), I can certainly understand that it would complicate things from a technical perspective and it would be a lot of work to implement. A shame really, because UX-wise favicons are a super nice feature if I may say so, but it's a small price to pay for having an otherwise great private search engine at hand, so you won't hear me complain (much :P).

**Comment by return42** [comment]
> While I'm not too sure about the privacy issues (because it would be togglable and disabled by default, so it would just be one more tool for the user/host to judge its merit and decide whether to use it or not),

IMO most users will enable such a nice feature without knowing what data they would leak.

That is why I think, if we implement such a feature it should be _protecting privacy by default_.   But this will need some technical superstructure (e.g. @mrpaulblack mentioned a icon server).

> but it's a small price to pay for having an otherwise great private search engine at hand, so you won't hear me complain (much :P).

:-) .. thank you for understanding this.

Beside the privacy aspect and the technical superstructure there are also coming some other -- more practical questions -- into play.  One thing I have in mind is: What Icon should be displayed when there is a redirect?

By example: in my instance I redirect all youtube results to an invidios instance (since those instances give their users more privacy, I discuss it here https://github.com/searxng/searxng/discussions/911).  

If we want to support result-icons, what icon does match the best on such redirected results without confusing the user?

---

Anyway I think result-icons would be a nice feature but I don't see that we have the resources to implement in the near future.

I close this issue for now .. but we are open for suggestions, may be there is a simple solution we don't think about right now.

**Comment by LencoDigitexer** [comment]
I added the favicon server selection in the settings https://github.com/f5ociety/Trydex/blob/master/searx/settings.yml#L2042, proxied the favicons https://github.com/f5ociety/Trydex/blob/master/searx/templates/simple/macros.html#L23

Prepare a pull request?

**Comment by return42** [comment]
> Prepare a pull request?

Oh yes, please .. I can't promise we will merge but I would like to revive the topic :+1:

**Comment by inson1** [comment]
I think its the most important missing feature

**Comment by omentic** [comment]
I'd like to see this issue reopened - even if it is a long-term feature, it seems there is interest from both users and developers?

As far as preserving privacy goes, I would suggest:
* SearXNG shipping with favicons for the most popular sites by default: pulled from ex. https://iconmap.io/ or elsewhere
* SearXNG *fetching* favicons of sites without entries in the favicon database, and caching them
  * This means requests made to many external websites at first, but as the cache grows, fewer and fewer
* Instance administrators then could contribute back their cached icons to https://iconmap.io/ or an internal SearXNG repository

I'm curious what others would think of making requests on every search to individual sites. SearXNG returns 35 search results by default. The favicon database linked about is quite large (half a million), and most sites that *would* track users are already in there. Popular sites would get quickly cached, so this would likely quickly dwindle down to a request or two per search, to what would probably be mostly small blogs. And if a large engine or two cached icons for a few weeks and contributed them back, there wouldn't be much of an incentive for smaller instances or particularly privacy-concerned instances to even turn this on at all (since most sites would have favicons).

**Comment by glanham-jr** [comment]
In addition to omentic's comment, I have a few questions as well.

1. Do we want to "expose" SearXNG instances to making calls to a lot of random websites all over the web, even if just fetching a favicon? There is already the task of all instances calling the relative search engines, but this would introduce a lot more requests to a lot of random non-engine sites. We typically think of privacy of the users, but should we consider privacy of the instance in this regard?
2.  To address the above, do we want to consider a separate `searxng-icon-server` hosted service to reduce risk to maintainers?
  - Regardless of privacy, implementing a `searxng-icon-server` could make the SearXNG updates trivial - having the icon server handle requests for favicons itself may allow SearXNG just to just add an external link to the favicon server on the HTML and call it a day, letting the client deal with fetching and the icon server dealing with results and caching.
  - Adding the icon server introduces a secondary network dependency for clients + now the `searxng` project will need to handle available icon servers. Who will host the primary icon server? Will we rely on other maintainers? Will we assume that most SearXNG maintainers will also host their own icon server and link to that?
3. Just a later question. How large will this cache grow in memory? Will we allow caching to disk? For reference, a favicon ~4Kib. 100k favicons is ~0.38Gib, 300k reaching ~1.14 Gib.

**Comment by return42** [comment]
> I have a few questions as well.

Similar questions we discussed these days on Matrix ("SearxNG public instances owners"), AFAIK @vojkovic is working on a solution ..

Further I tagged related threads by [result-favicons](https://github.com/searxng/searxng/issues?q=label%3Aresult-favicons)

**Comment by vojkovic** [comment]
Thanks @return42. Favicons are currently live on [https://priv.au](https://priv.au).

I will be monitoring a few different metrics on each of my servers over the coming days / weeks to see how this feature goes. I'll also have to implement a favicon proxy within the SearXNG codebase as I'm currently using a seperate application written in golang.
