### ISSUE TITLE
About pylint configuration

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#102]
Here a command to get some statistics:
`$ git grep "pylint: disable=" | cut -f2 -d\# | cut -f2 -d\= | tr , '\n' | sed 's/^ *//' | sort | uniq -c | sort -nr`

* `cut -f2 -d\#`: the comment at the end of line (can be broken)
* `cut -f2 -d\=` : after `pylint: disable=`
* `tr , '\n'` : split coma separated values into multi lines
* `sed 's/^ *//'`: trim spaces

Result:
```
     37 missing-function-docstring
     13 no-member
      9 invalid-name
      9 global-statement
      9 assigning-non-slot
      7 undefined-variable
      7 missing-module-docstring
      7 broad-except
      6 NOQA 
      6 attribute-defined-outside-init
      4 unused-import
      4 E1101
      3 protected-access
      3 no-self-use
      3 consider-using-with
      2 W0102
      2 unused-argument
      2 too-many-arguments
      2 C0116
      2 access-member-before-definition
      1 wrong-import-position
      1 W0223  
      1 useless-object-inheritance
      1 too-many-boolean-expressions
      1 stop-iteration-return
      1 see https://github.com/encode/httpx/blob/e05a5372eb6172287458b37447c30f650047e1b8/httpx/_transports/default.py
      1 R0903
      1 pointless-string-statement
      1 no-name-in-module
      1 missing-class-docstring
      1 inconsistent-return-statements
      1 import-outside-toplevel)
      1 from https://github.com/encode/httpcore/blob/4b662b5c42378a61e54d673b4c949420102379f5/httpcore/_backends/asyncio.py
      1 E0611
      1 E0401 C0413
      1 E0401
      1 C0301
      1 arguments-differ
```

.pylintrc to update (?)
* `missing-function-docstring`: 17 occurrences for `searx.engines.*` . Currently the pattern `# pylint: disable=missing-function-docstring` at the top of the file doesn't help in my opinion. Documentation about the `request` and `response` functions doesn't help. But documentation about custom functions can help. It is only my opinion.
* `unused-import`: all related to import ` _fetch_supported_languages, supported_languages_url`: I would disabled `unused-import` for `searx.engines.*` or find a way to tell pylint that `_fetch_supported_languages`, `supported_languages_url` are actually used.
* `global-statement`: do we really need a reminder about global variable usage?

actual issue:
* `invalid-name` is actually not required in `searx.engines.*` (7 occurrences / 9).
* `no-member`: related to preferences.py (see [constructor](https://github.com/searxng/searxng/blob/7c76cef746a90542f7db7a9ca876e763d0aad1a3/searx/preferences.py#L43-L44))
* `assigning-non-slot`: all related to `request.something = `, actually it should be `g.something =`.

`manage` script issue:
* `undefined-variable` is not required since there is PYLINT_ADDITIONAL_BUILTINS_FOR_ENGINES, but for some reason it is ignored: it is a bug.

**Comment by return42** [comment]
> .pylintrc to update (?)

No. :) ... the intention must be _"improve the code"_ .. disabling messages for all files means: we do not want to improve the code / even in new files (new development).

Engines and Plugins are _special_  and need a different treatment.  

>  Currently the pattern # pylint: disable=missing-function-docstring at the top of the file doesn't help in my opinion.

It will not help for existing files, except we add documentation to existing functions, but this is a hard job and includes the risk to fail.

>  I would disabled unused-import for searx.engines.* or find a way to tell pylint that _fetch_supported_languages, supported_languages_url are actually used.

Engines and Plugins have _name injections_ and need their own .pylintrc file where e.g. things names like `PYLINT_ADDITIONAL_BUILTINS_FOR_ENGINES="supported_languages,language_aliases"` are defined.

> actual issue:     invalid-name is actually not required in searx.engines.* (7 occurrences / 9).

For me a line on the top of  a python file like::

    # pylint: disable=invalid-name, missing-function-docstring

indicates, that this file is much improvable. 

> Documentation about the request and response functions doesn't help.

It will help to maintain .. by example: this is an example for a usefull module-doc-string of an engine:

https://github.com/searxng/searxng/blob/b1da97d0922020dabcdc971d16e3e7a95be58c1b/searx/engines/google_videos.py#L5-L20

On the long term we can include such doc-strings into the docs-build, but ATM we only have rare useful doc-strings. I haven't found one for the request & response function.  But here is an example where such a doc-string is needed to understand why a http header is added:

https://github.com/searxng/searxng/blob/b1da97d0922020dabcdc971d16e3e7a95be58c1b/searx/engines/wolframalpha_api.py#L44-L46

> no-member: related to preferences.py (see constructor)
> assigning-non-slot: all related to request.something = , actually it should be g.something =.

We will always have situations that an automated Lint process cannot capture from a technical point of view.  Here, we have to think about workarounds.  Adding "pylint-dissable" remarks might be annoying sometimes, but it is one workaround, that is available everywhere.

Over all: 

For me, the [.pylintrc](https://github.com/searxng/searxng/blob/master/.pylintrc) file is the _"holly grail"_. This file defines the quality I strive for.

For me improving code-quality is an ongoing process. Comments disabling some pylint messages are a _warning sign_ that something can be improved _here_.  The _improvable_ code could remain over a long time.  If there comes a day this code needs to be touched for some other reasons (e.g. a bugfix) I will also fix the lacks reported by pylint.

Since I can't lint only a hunk of a file, I first lint the whole file (adding comments to disable some linter messages).  After this,  I implement my new code in this file. This assures that my new code is conform to my _"holly grail"_.

**Comment by return42** [comment]
>`manage` script issue:
> * `undefined-variable` is not required since there is PYLINT_ADDITIONAL_BUILTINS_FOR_ENGINES, but for some reason it is ignored: it is a bug.

For me it works (edit to `PYLINT_ADDITIONAL_BUILTINS_FOR_ENGINES=""` and you will get some error messages.

BTW, I was looking here for anything I can improve, but don't see what can be improved.  What do you think,  is there anything left we can improve to to get this issue closed?  .. do you miss something?

**Comment by dalf** [comment]
> do you miss something?

My bad, it works without  `# pylint: disable=undefined-variable`.

So why add `# pylint: disable=undefined-variable` in `searx/engines/*.py` ?

**Comment by return42** [comment]
> So why add # pylint: disable=undefined-variable in searx/engines/*.py ?

We have engines tagged with `# lint: pylint`. In the past we needed to ignore `undefined-variable`.

Since https://github.com/searxng/searxng/pull/296/commits/7b235a1c36b09cfe2c6b4c97c3b6dad77e51d5ae (see line 591) this should no longer bee needed .. I will send a PR which cleans up this.

**Comment by dalf** [comment]
Another point: what about `missing-function-docstring` in `searx/engines/*.py` ?

> >  Documentation about the request and response functions doesn't help.

> It will help to maintain .. by example: this is an example for a usefull module-doc-string of an engine:

Do we need pylint to require documentation? If it makes sense to add documentation to a function we can add it without pylint especially since:
* this is the engine code: most of the time it is just `request`, `response` and sometimes `init`
* there is a review (pull request)

**Comment by return42** [comment]
>  If it makes sense to add documentation to a function we can add it without pylint especially since:
> - this is the engine code: most of the time it is just request, response and sometimes init
> - there is a review (pull request)

IMO engines are always _very special_ and I would enforce developers to document the engine.  We have done this already for some engines:

- https://searxng.github.io/searxng/src/index.html 

From this point of view I think it is good to raise a pylint messages when an engine is not documented (for historical or whatever reason) but tagged with a `# lint: pylint` 

For those engine files not tagged the by `# lint: pylint`  we have additional _disable options_

    PYLINT_SEARX_DISABLE_OPTION="\
    I,C,R,\
    W0105,W0212,W0511,W0603,W0613,W0621,W0702,W0703,W1401,\
    E1136"

Where we disable `C` what includes `C0116 missing-function-docstring`

**Comment by dalf** [comment]
>  I would enforce developers to document the engine.

Why when in most of the cases there is no documentation to add?

What will happen:
* either ignore `# lint: pylint`
* or copy paste `pylint: disable=missing-function-docstring` from another engine.

and we go back to the review.

**Comment by return42** [comment]
> Why when in most of the cases there is no documentation to add?

I have a different opinion, I think there is always something to document about the engine and how it works. 

> or copy paste `pylint: disable=missing-function-docstring` from another engine.

By example: if I develop a complete new engine module and want to have a _strict_ pylint test ...

https://github.com/searxng/searxng/blob/9ef7f38e4f20bad5a76867aa3e5049a92bc58e59/manage#L604-L607

I tag the file by `# lint: pylint` ...

https://github.com/searxng/searxng/blob/9ef7f38e4f20bad5a76867aa3e5049a92bc58e59/manage#L19-L29

If do not want to have a _strict_ pylint test I leave the file untagged.   This file will then be tested with additional `--disable="${PYLINT_SEARX_DISABLE_OPTION}" ` .. this is the case for most of the historical existing engines

https://github.com/searxng/searxng/blob/9ef7f38e4f20bad5a76867aa3e5049a92bc58e59/manage#L609-L613

If I have tagged my engine by by `# lint: pylint` it will be tested _strictly_. Where _strictly_ means also, a documentation is needed otherwise disable this warning message by  `#pylint: disable=missing-function-docstring`

**Comment by dalf** [comment]
My opinion:
* If the idea is to welcome contributors, we should make their life easy. The more obstacles between a contributor and a PR there are, the less we will have contributions.
* If we need documentation, there is no need to pylint to tap on shoulders.

I'm just talking about the docstring rules for the engines, not the whole pylint configuration.

But I understand this is not your opinion.
I leave this issue closed.

**Comment by return42** [comment]
> If we need documentation, there is no need to pylint to tap on shoulders.

OK, that is an argument I can understand .. I reopen this issue and will send a PR which cleans up the `disable=missing-function-docstring` ..
