### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Sabering1** [searxng/searxng#1063]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.05

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @Sabering1 ,
Thnaks for opening an issue in SearXNG core. Can you please provide more information about the issue and fill out the bug template, which is still empty atm (Did you use a public instance? which one?...).

Otherwise this looks like IP blocking from duckduckgo which we cannot really do anything about and in that case I would like to close the issue...

**Comment by simpvn** [comment]
> Hi @Sabering1 , Thnaks for opening an issue in SearXNG core. Can you please provide more information about the issue and fill out the bug template, which is still empty atm (Did you use a public instance? which one?...).
> 
> Otherwise this looks like IP blocking from duckduckgo which we cannot really do anything about and in that case I would like to close the issue...

https://github.com/searxng/searxng/issues/1053#issue-1191207947

**Comment by return42** [comment]
closed in favor of https://github.com/searxng/searxng/issues/1053
