### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by lifeizhaopaopao** [searxng/searxng#1088]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.04.12-1388b44f

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.TimeoutException
  * Percentage: 50
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 50
  * Parameters: `(None, None, 'www.google.com.hk')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
> How To Reproduce

Without giving the information the form asks for, we can't help / we can reopen this issue if you give us the needed hints.

**Comment by lifeizhaopaopao** [comment]
No solution, but thanks anyway

**Comment by return42** [comment]
The only information you give is from the technical report and this reports says that there was an timeout in the google request .. this could be caused by various reasons, may be it was only a temporal issue.

For more help, we need more information .. the template asks for:

How did you install SearXNG?

What happened?

How To Reproduce?

Screenshots & Logs

Additional context?
