### ISSUE TITLE
implement "feeling lucky" feature

### ISSUE THREAD

**Issue by sylsau** [searxng/searxng#1128]
Hello everyone and thank you for the great work you're doing!

I've started using SearxNG recently and I love it!
In fact I'd like it to be my main search engine, although I'm missing something coming from DuckDuckGo. As you can guess, I wasn't using DDG for the quality of its results, but mainly for its bang capabilities.
While SearxNG allows for even faster bang redirects than DDG (using for example `!!w` for those who don't know), I also make a heavy use of the "feeling lucky" DDG bang syntax, where `[keywords] !` gets you directly to the first result.

[A comment](https://github.com/searx/searx/issues/870#issuecomment-286585153) in the issues of the original *searx/searx* mentionned that it wasn't allowed for "security reasons", namely that you could get redirected to a malicious website if the results happen to be harmfully skewed for the keywords you entered.

Not only have I never had this problem in many years of using it, but maybe it should be the user's choice whether that can happen or not. I was wondering what was your take on this issue. 

Implementing the "feeling lucky" bang would be a great addition that would make me switch to SearxNG as my main search engine, I'm sure many others are feeling this way too.

Thank you for your attention and for the great work!
S.

**Comment by return42** [comment]
> https://github.com/searx/searx/issues/870#issuecomment-286585153 in the issues of the original searx/searx mentioned that it wasn't allowed for "security reasons" ..
> but maybe it should be the user's choice whether that can happen or not

personally I share your opinion .. I think "feeling lucky" is a feature we should consider to implement .. I don't see a security problem with the redirect, since we already redirect in the bang feature.

Not clear to me is, to what page ddg does redirect .. I assumed it is the first result item of a search query .. but it isn't.  By example when I (from DE) search for `foo` in ddg the first result is the a wikipedia article (DE):

![grafik](https://user-images.githubusercontent.com/554536/164443293-23309fa3-aa5c-4362-8a01-0d49246da538.png)

But when I use "feeling lucky" and type `foo !` ddg redirects my to an english dictionary from merriam-webster.com (https://www.merriam-webster.com/dictionary/foo).

**What are the rules SearXNG should use to select a page to redirect?**

**Comment by mrpaulblack** [comment]
I agree this is a cool feature. We should keep the impl. KISS tho so just redirecting to the first result is IMO the best option. It is easy to understand by the end user and keeps the impl. simpler.

We should in that case also add this feature to the search syntax page on instance specific search documentation :+1:

**Comment by sylsau** [comment]
@return42 Actually I never noticed that but that's absolutely right.
As mentionned by @mrpaulblack : selecting the first result seems the KISSiest in this case.

As for the bang syntax, being French I can tell you that we always put a space between the last words in a sentence and the final exclamation point ("Comme ça !") contrary to english ("Like that!"). That might actually be how I inadvertently discovered bang in DDG.
Also in line with the current bang redirects implementations using `!!` as suffix, maybe we could use `[keywords] !!` to "feel lucky". It would certainly seem consistent, although not a huge deal.

**Comment by Bandit** [comment]
I really want this feature, and currently use a modified DDG query with the 'feeling lucky' bang built in as my default engine. With my usage I often add a specifier like "imdb martian" to take me straight to the IMDB page for The Martian if I think the top result may not be what I want.
