### ISSUE TITLE
`make format.python` is broken

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#1142]
`make format.python` runs

`black --target-version py37 --line-length 120 --skip-string-normalization --exclude searx/static,searx/languages.py --include searxng.msg searx searxng_extra tests`

doesn't fix the code

it works without `--include searxng.msg`:
`black --target-version py37 --line-length 120 --skip-string-normalization --exclude searx/static,searx/languages.py searx searxng_extra tests`

**Comment by return42** [comment]
Sorry, my fail .. fixed in  #1143 / never seen that there is only one file tested:

![grafik](https://user-images.githubusercontent.com/554536/164885992-ca2917c0-1554-4016-84f7-c3e3497103b9.png)

such _blinky_ messages are nice on colorized utf-8 terminals but hard to read on _dump_ terminals.

![grafik](https://user-images.githubusercontent.com/554536/164885807-a88e9a15-568f-4209-b573-2487f167d3f8.png)

**Comment by dalf** [comment]
> such blinky messages are nice on colorized utf-8 terminals but hard to read on dump terminals.

See:
* https://github.com/psf/black/issues/223
* and perhaps https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30045
