### ISSUE TITLE
[question] Getting error 429 (Too Many Requests) in HTTPS using Limiter + Redis [NGINX]

### ISSUE THREAD

**Issue by Fijxu** [searxng/searxng#1163]
After setting my server (without docker) i enabled the limter, installed redis (the built in redis and the redis package from my distro), give the right permissions BUT, when i try to search using HTTPS, i get error 429.

**What i tested already**

1. Switch between the searxng redis and the redis package (Arch Linux)
2. Delete different settings from my nginx config (Security Headers https://observatory.mozilla.org/analyze/search.zzls.xyz) temporally
3. Giving the right group to the user `searx`

![02-234203](https://user-images.githubusercontent.com/61166695/166403496-322adca3-da0c-4262-b75f-523a1264733b.png)

**Comment by mrpaulblack** [comment]
This is from the limiter blocking your browser. Please make sure that your browser is passing all checks from:

https://github.com/searxng/searxng/blob/8a79eb4d7b0265afc200ecf6c1d729274a065b18/searx/plugins/limiter.py#L39-L75

You could first test by using something like firefox or chromium without any addons or changes and if this works, then try to figure out what is different in your setup compared to ff or chromium...

If I would need to guess its maybe your user agent... If its matched by this, it is marked as bot and the request for a search ends in a 429:

https://github.com/searxng/searxng/blob/8a79eb4d7b0265afc200ecf6c1d729274a065b18/searx/plugins/limiter.py#L28-L36

SO yeah if you find a solution please also post it here for others, if they have the same problem...

Otherwise please share more about your setup, especially your request headers from your browser please :+1:

**Comment by Fijxu** [comment]
After seeing `searx/plugins/limiter.py#L39-L75` i figured out I missed to set the `proxy_set_header` in the NGINX config file for SearxNG to detect the real IPs addresses of the clients.
This is how my config looks now and its works as intended :)

```
...

location / {
        proxy_pass http://127.0.0.1:8888/;

        # Proxy headers for the Limiter 
        proxy_set_header Host $host;
        proxy_set_header Connection       $http_connection;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme         $scheme;

...
```

Thanks!

**Comment by Octothorn** [comment]
> 

FYI, I am finding I only need `proxy_set_header Connection       $http_connection;`

**Comment by return42** [comment]
> FYI, I am finding I only need `proxy_set_header Connection $http_connection;`

Please set all headers recommended in the installation instructions

- nginx: https://docs.searxng.org/admin/installation-nginx.html#nginx-s-searxng-site 
- apache: https://docs.searxng.org/admin/installation-apache.html#apache-s-searxng-site

otherwise, sooner or later you will have problems .. with the limiter with internal URLs or whatever.
