### ISSUE TITLE
Ability to invert ! and !! usage

### ISSUE THREAD

**Issue by julianfairfax** [searxng/searxng#1170]
**Is your feature request related to a problem? Please describe.**
Kind of. I'm used to using ! for bangs since I was previously using DuckDuckGo, but on SearXNG it's !!

**Describe the solution you'd like**
Since ! is used for something else, it should be possible to invert the usages of ! and !! with a preference

**Describe alternatives you've considered**
Relearning how I type bangs.

**Additional context**
! is more convenient than !!. I know ! is useful to search in categories and from engines, but I don't do that as often so I'd rather have the more convenient option for what I use most often.

**Comment by return42** [comment]
Thanks for your request but I see some issues coming with configurable search syntax. To just name two: beside making implementation of SearXNG more complex we can't provide any longer the Search-URL box, since the search URL /the syntax) than depends on the property to invert ! and !!

> ! is more convenient than !!

SearXNG and searx users are used to use the `!` for categories or engines, and `!!` for external bangs since the beginning .. BTW external bangs are out of the scope of privacy. 

----

Updated from a comment of mine on Matrix: 

Mixing `!` (privacy) and `!!` (no privacy) will confuse the users .. and the documentation  of the syntax is no longer valid.  By example:

When a SearXNG user who is used to use `!` to select a category visits (e.g.) your instance (where the syntax of `!` and `!!` is different) and types a search query with `!` his privacy is voilated (he is redirected to a page he might never want to be). 

If the user then looks at the documentation (instance's `/info` page or [project-docs](https://docs.searxng.org/user/index.html#search-syntax)) about the search syntax and reads there that `!` is used to select categories or engines .. but he is redirected what should he think?

**Comment by Jorenar** [comment]
@return42 
Couldn't it be implemented as opt-in user preference?

**Comment by return42** [comment]
@Jorengarenar Theoretically, this could be done, but it would confuse users when they switch between the instances offered on https://searx.space

The search syntax is too elementary to be changed via options / for a complete implementation the description would have to be adapted as well --> https://darmarit.org/searx/info/de/search-syntax.

----

OT: Personally, I think we have far too many settings that complicate the code and are only used by less than 1% of users.  But this is just my personal opinion.

**Comment by Jorenar** [comment]
@return42
On the other hand, it brings inconsistency with all other search engines (and custom bang extensions) where single `!` is redirecting bang. I use redirecting bangs as convenient shortcuts to webpages all the time (it's a killer feature of DuckDuckGo; it replaced most bookmarks for me), while narrowing engines seems more like something I'd use only occasionally when normal search is not enough.

I don't think it would even require any change to existing documentation as the option would be self documenting. If an user explicitly toggles option "switch around behaviour of `!` and `!!` in search syntax" they certainly know what that entails.
Privacy minded users would review preferences anyway before using any new instance.

I'd send a PR, but I have no clue how to add a toggle to `/preferences` page.

**Comment by return42** [comment]
> I'd send a PR, but I have no clue how to add a toggle to `/preferences` page.

@Jorengarenar No need for / sorry, but we won't accept changing the search syntax.

> On the other hand, it brings inconsistency with all other search engines (and custom bang extensions) where single ! is redirecting bang.

I can fully understand that is unused for ddg users to type double bangs `!!`, but as more you used to use SearXNG you won't stop on this any longer.

Please understand that SearXNG has a privacy focus, in this focus a external bang has not the first priority (since it riderects directly to an external page where the user might be tracked).  As more, we have a single bang to select an search engine or a category from the very first days.  Or to say it with other words: its unused to a SearXNG user to use a single bang for an external bang.
