### ISSUE TITLE
Support 'default_lang: "all"' in settings.yml

### ISSUE THREAD

**Issue by nexryai** [searxng/searxng#1213]
**Is your feature request related to a problem? Please describe.**
I am Japanese. I usually use Japanese to perform searches. However, not all of the information I want to know can be found on websites written in Japanese.
So I use English for some searches.
Google will retrieve English search results when it identifies an English search term as entered when the language setting is set to "All Languages", but Searxng will retrieve Japanese websites when accessed from Japan, even if the search term is entered in English.

**Describe the solution you'd like**
Add "All Languages" to Searxng's language settings.

**Comment by nexryai** [comment]
From what I have tried in my browser, it appears that this can be accomplished by removing `lr=LANG` from the URL parameter of the search request.

**Comment by nexryai** [comment]
This seems to be already achieved with `default_lang: "all"`!
Sorry!

**Comment by dalf** [comment]
ping @return42

**Comment by nexryai** [comment]
This seems to be already implemented as `Default language`, but why can't I use `default_lang: "all"` in `settings.yml`?

**Comment by nexryai** [comment]
https://github.com/searxng/searxng/blob/master/searx/engines/google.py#L190

I don't know if this is related, but this appears to be caused by `google.py`. If you set the language to ALL, the region is automatically set to US.

**Comment by return42** [comment]
> If you set the language to ALL, the region is automatically set to US.

If you visit google.com (or any other web site) directly, your browser sends a HTTP `Accept-Language` header.

This header and other information you did not typed in your query (e.g. location of your IP) is used by google & Co. to (track you and) give "better" results.  If google & Co. don't see such  "HTTP Headers" it might come to the conclusion that the request comes from a bot and blocks the IP (aka CAPTCHA).

For privacy reasons, SearXNG don't want to send any data from the user to the engines (e.g. google), except those the user typed in or selected from a menu (region & language).


On the other side SearXNG needs to send additional data (HTTP `Accept-Language` header), otherwise it will be rated as a bot request and be blocked by a CAPTCHA.

https://github.com/searxng/searxng/blob/f814ac703b25640d28ab3a4a096f693808cde6db/searx/engines/google.py#L244-L252

TBH its most often much more complex and each search engine (google, startpage, bing ...) is completely different from the other .. and we can only do some *reverse engineering* 

To *get things done* and have a resilient solution we often simplify things  / e.g ...

https://github.com/searxng/searxng/blob/f814ac703b25640d28ab3a4a096f693808cde6db/searx/engines/google.py#L190-L191

OT: I'm working on a review of the language & region concepts in SearXNG .. but it will take a very long time before we see this in master (its a complex work with many details / the concepts we have and each engine needs to be reviewed .. I can't promise anything, but I hope I can improve what we have .. let's see).

**Comment by nexryai** [comment]
This seems to be a complex and difficult issue. I hope in the future this issue will be resolved. Thanks for maintaining this great search engine!

**Comment by return42** [comment]
> So I use English for some searches.

In the meantime SearXNG supports language detection from search term (`:auto`) and https://github.com/searxng/searxng/pull/2269 has improved the language support (especially jp & zh) in the major search engines like google.
