### ISSUE TITLE
Wikispecies

### ISSUE THREAD

**Issue by julianfairfax** [searxng/searxng#1222]
**Working URL to the engine**
https://species.wikimedia.org

**Why do you want to add this engine?**
Out of all of the Wikimedia projects, Wikimedia Species is one of only two to not appear in any engine category in SearXNG, with the other being Wikimedia Commons.

**Features of this engine**
It has [803,813](https://species.wikimedia.org/wiki/Special:Statistics) articles, covering [Animalia](https://species.wikimedia.org/wiki/Animalia), [Plantae](https://species.wikimedia.org/wiki/Plantae), [Fungi](https://species.wikimedia.org/wiki/Fungi), [Bacteria](https://species.wikimedia.org/wiki/Bacteria), [Archaea](https://species.wikimedia.org/wiki/Archaea), [Protista](https://species.wikimedia.org/wiki/Protista) and all other forms of life.

**How can SearXNG fetch the information from this engine?**
`https://species.wikimedia.org/w/index.php?search=%s` with `%s` being what you want to search.

**Applicable category of this engine**
General, science.

**Comment by dalf** [comment]
Most probably it can integrate with the mediawiki engine:
https://github.com/searxng/searxng/blob/61535a4c206aa247a6fa87697b70668048086e27/searx/settings.yml#L542-L557

---
Side note: this is where I would to be able to create repository of additional engines (  https://github.com/searxng/searxng/issues/534 ).
Because there are many of databases about species:
* https://tree.opentreeoflife.org/opentree/argus/opentree13.4@ott93302 to pick one
* of even wikidata : https://www.wikidata.org/wiki/Q102857
  * see "instance of", "NCBI taxonomy ID", etc..

from that we can imagine:
* some changes on how to merge the result.
* some dedicate templates to display the species, etc...
