### ISSUE TITLE
Search bar auto focus issue make it unusable for tiling window users

### ISSUE THREAD

**Issue by amalgame21** [searxng/searxng#1270]
Actually I use keyboard-driven qutebrowser
But I use chromium here for clear demostration since the dark theme of qutebrowser is hard to disable 
The outcome are the same

No mouse click action below, all keyboard shortcut only:
![out2](https://user-images.githubusercontent.com/93383215/171522949-8d6b741f-4382-487a-8a38-a3c51613fcd1.gif)

As you can see, when there is only one window (browser), and I perform a search, in the search result page, the cursor is automatically focused on the search bar.
When I use keyboard shortcut to open another window, and focus back to the browser, the search result become hidden by the huge auto suggestion block. 

However, If I open another window first, and go back to the browser, then perform a search afterwards, there will be no auto focus issue.

I think the "auto focus search bar" only be triggered while loading the search result with wide screen, and the focus persist when the screen become narrow, which actually is not a problem. The big problem is the search result are blocked. In qutebrowser, I have to press "Tab" key few times to get rid of the blank area and go on browsing.

oscar theme did not have this problem, but I know the theme was discontinued, very sad. 

Tiling window manager I used: i3

SearXNG installed by AUR searxng-git package.

**Comment by dalf** [comment]
Possible solution: the autocompletion takes the whole screen only on mobile, not on desktop. 

Implementation:
[open-props](https://open-props.style/#media-queries) has a media query to detect touch screen : `@custom-media --touch    (hover: none) and (pointer: coarse);`

So the fix would replace the media query for this block https://github.com/searxng/searxng/blob/96dc4369d535dc20178a3e7df793c8f2427d2c79/searx/static/themes/simple/src/less/search.less#L284-L309

for this one:
```less
@media screen and (max-width: @phone) and (hover: none) and (pointer: coarse) {
    ...
}
```

so the results are only hidden on a device with a small screen and with a coarse pointer without the hover feature = on mobile.

**Comment by mrpaulblack** [comment]
No I think the issue is about the focus on the input field for the search, right? so right now the autofocus is not set on mobile and always set on desktop via JS. I think a fix would be to either not set autfocus at all (which I would not like), or to only set focus to the search input field on the index page on desktop (that is IMO a must)...

https://github.com/searxng/searxng/blob/96dc4369d535dc20178a3e7df793c8f2427d2c79/searx/static/themes/simple/src/js/main/search.js#L89-#L91

**Comment by dalf** [comment]
From what I see, on various search engines on desktop (google, ddg, qwant, brave, kagi, startpage, bing):
* the input field gets the focus on the front page.
* the input field doesn't get the focus on the result page.

so 

> to only set focus to the search input field on the index page on desktop (that is IMO a must)...

👍 

---

Also, I feel the full size auto-completion could be enabled on @ultra-small-phone rather than @phone

**Comment by mrpaulblack** [comment]
I actually like the full size autocomplete for all phones (its basically a copy from google design) -> since the on screen keyboard is going to use up all vertical space without the full screen autocomplete. So I would like to keep it at the phone width :+1: 

and the input field for googles landing page on mobile does not get autofocus. I would like to emulate that since otherwise the full screen autocomplete will open immediately on mobile landing page. So this is why I would like to only have autofocus on desktop landing page -> since its expected there, but not in any other place or screen format IMO.

(So yeah I basically agree with you, except the change for the full size autocomplete width :+1: )

**Comment by dalf** [comment]
> except the change for the full size autocomplete width

what about `@media screen and (max-width: @phone) and (hover: none) and (pointer: coarse) {`  :
* full size on a phone
* drop down on desktop even on small screen
?

---

[EDIT] see the PR

**Comment by mrpaulblack** [comment]
@amalgame21 can you please try again with latest master version. Is the issue now fixed for you?

**Comment by amalgame21** [comment]
> @amalgame21 can you please try again with latest master version. Is the issue now fixed for you?

Thank you [dalf](https://github.com/dalf) and [mrpaulblack](https://github.com/mrpaulblack) ! the issue is fixed for my use case!!!!
