### ISSUE TITLE
Going to "Preferences" menu gives error if UI language is set to Tamil

### ISSUE THREAD

**Issue by Ridhubharan** [searxng/searxng#1366]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.06.20 (all versions I have tried)

**What happened?**
Clicking on "gear" icon to go to "Preferences" menu gives `500 internal server error`

**How To Reproduce**
1. Change UI language to "Tamil"
2. Click on "gear" icon

**Expected behavior**
Go to "Preferences" menu

**Screenshots & Logs**
![Screenshot from 2022-06-25 20-41-14](https://user-images.githubusercontent.com/41824719/175779803-abcda496-0d4e-4ad3-9e47-1ac0da81ab21.png)

**Comment by dalf** [comment]
Related to
https://weblate.bubu1.eu/translate/searxng/searxng/ta/?checksum=2566578b8dc1b6ff

The translation should be `வாதங்களின் {functions} கணக்கிடவும்` instead of `வாதங்களின் {செயல்பாடுகளை} கணக்கிடவும்` (what is inside the bracket must not be translated).

---

Out of topic: however in https://weblate.bubu1.eu/translate/searxng/searxng/ta/?checksum=c171f10d9323771a the link to wikipedia _could_ be https://ta.wikipedia.org/wiki/%E0%AE%AE%E0%AF%80%E0%AE%AF%E0%AF%81%E0%AE%B0%E0%AF%88_%E0%AE%AA%E0%AE%B0%E0%AE%BF%E0%AE%AE%E0%AE%BE%E0%AE%B1%E0%AF%8D%E0%AE%B1_%E0%AE%A8%E0%AF%86%E0%AE%B1%E0%AE%BF%E0%AE%AE%E0%AF%81%E0%AE%B1%E0%AF%88 instead of https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol

**Comment by dalf** [comment]
@Ridhubharan : it should be fixed in the master branch. If you use public instances, you have to wait for update.

**Comment by dalf** [comment]
I close the issue: various public instances work as expected (pick at least the version 2022.06.25).
Feel free to reopen.
