### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by NoremaCam98** [searxng/searxng#1419]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 100
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @NoremaCam98  ,
Looks like the instance you are using has some network issues that result in a timeout. There is a timeout for all engines defined here: https://github.com/searxng/searxng/blob/master/searx/settings.yml#L130= . Brave did not return results in that time and therefor this error is thrown... If its a public instance you can use another one here: https://searx.space/. If its your instance you can increase the timeout to a greater number (if you have a slow network for example). Since we cannot really do anything about this I am going to close this issue; Closing.
