### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by hustle03x** [searxng/searxng#1429]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 25
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mrpaulblack** [comment]
Hi @hustle03x ,
It looks like the instance you are using got IP blocked by Mojeek. If its your instance you can add proxy server to disperse the traffic between multiple public IPs, otherwise you can ask the instance maintainer of the instance you are using to do that for you. But since we as developers cannot really do anything about this I will close this issue; Closing.
