### ISSUE TITLE
Re-Enable JSON and RSS for F-Droid App

### ISSUE THREAD

**Issue by 1seeyth** [searxng/searxng#1498]
Why did you disabled JSON and RSS by default? I had to revert my whole public instance after I got some complaint from users who use F-Droid's Searx search app. They are definitely not "bots" what you are thinking??

Why break things? Previous version was great.
How about reverting it and let the admin who installed searxng decide what to do!?!?

**Comment by tiekoetter** [comment]
https://github.com/searxng/searxng/blob/b6d59decda2be89a9b96e29b7a12538ba4af2c5c/searx/settings.yml#L48-L51

**Comment by return42** [comment]
> who use F-Droid's Searx search app.

You are the first reporting that there is a [(unofficial) App](https://framagit.org/beriain/search.searx/-/commits/master) using the JSON format.

> How about reverting it and let the admin who installed searxng decide what to do!?!?

Most admins don't aware of the problem:

- https://github.com/searxng/searxng/issues/95
- https://github.com/searxng/searxng/pull/226

and will report issues.

BTW: the development of the App seems to be stalling, could you make contact with the author?

**Comment by unixfox** [comment]
There is no plan to enable back JSON and RSS by default due to the reasons given in https://github.com/searxng/searxng/issues/1498#issuecomment-1182760928

Use an instance that have them enabled or install SearXNG then enable JSON and RSS like shown in https://github.com/searxng/searxng/issues/1498#issuecomment-1182657795
