### ISSUE TITLE
Redirect to alternative front-ends option!

### ISSUE THREAD

**Issue by f2e6** [searxng/searxng#1575]
![image](https://user-images.githubusercontent.com/95947898/181661984-edae5dda-9a0f-4794-86fd-3db8178365aa.png)

* I would love to have a similar feature like this picture implemented into searxng. This feature lets you choose FOSS alternative front-ends to replace links with. 
* One thing I would love to be changed from the way librex does it, is to allow us to use custom redirects. (ex. if it doesn't list nitter as an option, i could click "+" to add new row, and type twitter.net in one box, and nitter.net in the other.

**Comment by return42** [comment]
I understand this request .. but IDK "how" .. here are my thoughts:

On the server side SearXNG does not store any settings of the user session .. the only place where SearXNG can store settings is the cookie on client side and the cookie size is limited to ~4k.

- IDK where we can store all the URLs a user wish to redirect.

Another conflict I see: 

A user can copy the Search-URL (e.g. https://darmarit.org/searx/search?q=foo&language=de-DE&time_range=None&safesearch=2&categories=general) and send this URL to other users .. the intention of this feature is, that all users get the same results.  When the links in the result list are personalized the sender gets FOSS links and the other users get non-FOSS links.

related:

- https://github.com/searxng/searxng/discussions/911
- https://github.com/searxng/searxng/discussions/970
- https://github.com/searxng/searxng/issues/1765

**Comment by ghost** [comment]
I've been thinking about writing a plugin that does this by using https://github.com/benbusby/farside for the replaced URLs. No need to store lots of config for each user, just a single toggle for whether to use the plugin or not. Plus giving a different random front-end each time like Farside does means that you aren't being tracked by a single owner of a front-end service.

This seems like it should be relatively simple to implement, with similar code to the hostname redirect plugin. I just have never found the time to actually do it.

**Comment by f2e6** [comment]
This sounds great and the random front-end is nice, but id still like if there were at least an option to set your own. (I am a part of vern.cc and would want to use there instances when possible)

**Comment by AlyoshaVasilieva** [comment]
Farside is also a single point of failure if you just rely on the official instance (as I write this it's down)

---

If allowing users the option to set their own instances is too complex, it'd be nice if the admin could set instances and users just had the option of "enable/disable alternative front-end URL redirects".

**Comment by amogusussy** [comment]
@return42

Librex does it with the cookie header in each request.

You could maybe limit the number of possible redirections to account for the 4kb max cookie size.

**Comment by nfbyte** [comment]
I think this is better done in a browser extension (such as [Redirector](https://github.com/einaregilsson/Redirector) or [LibRedirect](https://github.com/libredirect/browser_extension)).

**Comment by Bnyro** [comment]
Unfortunately browsers on mobile devices often don't support extensions. Getting LibRedirect running on Firefox on Android is very hacky since it's not part of the officially provided extensions.
Any other browsers on mobile completely lack the possibility to use plugins to redirect to other frontends as far as I know.

**Comment by dannymate** [comment]
For those unaware [Predirect](https://github.com/libreom/predirect) is like LibRedirect but compatible with Manifest V3 and work on Firefox Android without hacky-ness. 

While I use an extension to handle this I can understand why others could benefit from this being built into SearXNG.

Edit: I also self-host my own alternative front-ends so the ability to set a specific instance for redirect would be handy.

**Comment by radiumatic** [comment]
Can't this be done with the same approach used for selective engine query? All SearxNG instances having a list of alternative frontend instances for each popular platform and allowing to either select a specific one, "best" (many projects have a bot for status check) or a custom one.

**Comment by Bnyro** [comment]
@radiumatic ... --> https://github.com/searxng/searxng/issues/1575#issuecomment-1198978876

**Comment by radiumatic** [comment]
> @radiumatic ...

Yes, I read that. Having the pre-fetched list on the server solves the storage issue. I don't think that is a conflict. We already have engine settings. For example, a user might enable piped search rather than youtube and send that to others. How is that any different? 

I think having community-curated lists for url rewrite and block would be the best idea. For customized ones, compression can be used? Text-only compression is relatively good.

**Comment by radiumatic** [comment]
> @radiumatic ...

Yes, I read that. Having the pre-fetched list on the server solves the storage issue. I don't think that is a conflict. We already have engine settings. For example, a user might enable piped search rather than youtube and send that to others. How is that any different? 

I think having community-curated lists for url rewrite and block would be the best idea. For customized ones, compression can be used? Text-only compression is relatively good.

**Comment by return42** [comment]
> or customized ones, compression can be used? Text-only compression is relatively good.

cookie size is limited to ~4k / and is already full of engine settings and other properties!

> I think having community-curated lists for url rewrite and block would be the best idea. 

We already have the discussions 

- https://github.com/searxng/searxng/discussions/911
- https://github.com/searxng/searxng/discussions/970

.. feel free to add your suggestions to new discussions.

**Comment by return42** [comment]
I close this feature request in favorite of https://github.com/searxng/searxng/issues/2351#issuecomment-1510826350
