### ISSUE TITLE
The search engine broke

### ISSUE THREAD

**Issue by xdetrtrtete** [searxng/searxng#1598]
The search broke pls fix it  and the site are not loading problem

**Comment by return42** [comment]
> The search broke pls fix it and the site are not loading problem

Can you please describe in more detail what you have done and what your problem is ... then I can reopen this issue.

----

PLEASE FILL THESE FIELDS, IT REALLY HELPS THE MAINTAINERS OF SearXNG

----

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

If you are running on master branch using git execute this command
in order to fetch the latest commit ID:
```
git log -1
``` 
If you are using searxng-docker then look at the bottom of the SearXNG page
and check for the version after "Powered by SearXNG"

Please also stipulate if you are using a forked version of SearXNG and
include a link to the fork source code.

**How did you install SearXNG?**
Did you install SearXNG using the official wiki or using searxng-docker
or manually by executing the searx/webapp.py file?

**What happened?**
A clear and concise description of what the bug is.

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots & Logs**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**
Add any other context about the problem here.
