### ISSUE TITLE
Remove themes

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#162]
Currently there are two themes: oscar and simple.

It is possible to choose at runtime which themes to use.

This issue suggests:
* to remove this choice to keep only one theme.
* keep the settings `static_path` and `templates_path`, so it is possible to another runtime at setup time, not runtime.

Why:
* the plugins and themes conflict each other:
   * looking at the source code of plugins https://github.com/searxng/searxng/tree/master/searx/static/plugins/js
   * everything is wired for the oscar: the plugins except jquery + the css classes from oscar
* it duplicates the maintenance: for example https://github.com/searxng/searxng/pull/136 despite its title, it is not exactly a copy of the simple layout to oscar (the "Special Queries" is new and should be back ported).
* we can focus one theme and make it right.

[EDIT] Remove the themes but the styles: light, dark (and we add "auto" using the browser settings).

**Comment by return42** [comment]
What theme would you prefere to drop?

OT: the word _theme_ is IMO a bit misleading, if we have only one theme we should better choose the word _client_ I think.

**Comment by dalf** [comment]
I would the simple theme without convection,  I think it can't be done now.

oscar
  * pros:
     * supports ARIA recommendations
     * RTL languages.
     * supports infinite scroll
     * image details
  * cons: 
     * bloated.
     * use bootstrap 3: deprecated.
     * the keyboard navigation UI is broken visually.

simple:
  * pros:
     * light
     * better mobile UI
     * keyboard 
  * cons:
     * see issue 1025 of searx.
     * the pros of oscar
  * note: see https://github.com/paulgoio/searx

Bootstrap 5 is lighter and without jquery, but it requires to migrate to the version 4 then to the version 5... wouldn't be easier to just upgrade the simple theme?

**Comment by return42** [comment]
I would also vote to drop oscar since it is really a mess.

What might the users say? @unifox do you have a feeling about?

_From developers scope reducing the themes to one and continue with the "simple"-theme would be a great relief._

**Comment by B0pol** [comment]
I prefer oscar theme

**Comment by return42** [comment]
>  I prefer oscar theme

Since the title of this PR "to remove" I have to ask; you prefer to stay with the oscar the and are not interested in other themes .. right?

If so .. what drawbacks do you see with the 'simple' theme?

**Comment by B0pol** [comment]
yes

> what drawbacks do you see with the 'simple' theme?

functional:
- no dark theme
- no image details

personal opinion:
- looks uglier, especially on desktop.
- not centered

**Comment by return42** [comment]
@dalf, @B0pol has some valid arguments I think / I have also some similar remarks about the simple theme on the other side I see this technical crap in implementation of the oscar theme.

I would suggest to have a strategy for a change to simple theme ..

1. no more enhancements for the oscar theme (left as-is)
2. improve simple theme to fit user's needs
3. At some day in the future: drop oscar / make simple theme the default

To have a plan, do you like to copy (and update) the issue 1025 from searx to SearXNG?

**Comment by mrpaulblack** [comment]
I did https://github.com/paulgoio/searx, which is just a few lines of CSS of the simple theme changed to make it look a little bit more modern on mobile and desktop -> https://start.paulgo.io. I actually prefer the simple theme/client, because:

* It feels more responsive than the oscar theme
* It was easier for me to understand it and go in and change the code
* The most important part about the site is the actual content and I feel like with the oscar theme there is just to much stuff going on, the simple theme on the other hand gets the job done without any distractions
* And in the simple theme images span over the entire available screen, which is way better, then just to put it in a small canvas like oscar does


Things that I think need to be changed with the simple theme:

* sticky footer at the bottom of the page
* functional settings from the oscar theme; like opening pages in a new tab and infinite scroll
* move in the content a little from the right so its not right against the left screen border
* give the user the choice to view the page a image is from instead of the actual image source (most of the time I don't want the original image but rather the article its from for example)
* redo color theme and just overall bigger UI elements; round corners and so on (right now its a little blunt)
* maybe some light css animations?
* add dark and black theme

**Comment by unixfox** [comment]
The theme simple doesn't have autocomplete on the home page compared to oscar.

**Comment by return42** [comment]
For me it works ..

![grafik](https://user-images.githubusercontent.com/554536/158573528-338d2041-52d7-4c32-b7f4-dfb1af59f87b.png)

**Comment by unixfox** [comment]
> For me it works ..
> 
> ![grafik](https://user-images.githubusercontent.com/554536/158573528-338d2041-52d7-4c32-b7f4-dfb1af59f87b.png)

Not for me on https://paulgo.io with the default settings, so with autocomplete to google.

**Comment by tiekoetter** [comment]
@unixfox but it does work. Do you mean something different?


![IMG_0317](https://user-images.githubusercontent.com/77782671/158580342-4733623a-25c3-4398-a33d-0cddc68e5576.png)
![IMG_0318](https://user-images.githubusercontent.com/77782671/158580443-d41ad93c-e880-4993-84c9-a2ef210a7190.png)

**Comment by unixfox** [comment]
Sorry guys, it works now... I don't know why.

**Comment by ononoki1** [comment]
When using oscar theme, one can select the description, which is impossible for simple theme.

<img width="552" alt="a" src="https://user-images.githubusercontent.com/82757890/166103795-12001afc-575e-42f3-b659-ff4850d65f1e.PNG">

**Comment by mrpaulblack** [comment]
yes its already bugged (https://github.com/searxng/searxng/issues/794) and there was a fix that got reverted because of a regression: https://github.com/searxng/searxng/issues/778 -> https://github.com/searxng/searxng/pull/1015

I think this is not in the way of dropping oscar tho, since its IMO a minor thing that will be fixed with simple in the future... If you already have a fix please feel free to open a PR :+1:
