### ISSUE TITLE
Allow hostname_replace to also replace subdirectories

### ISSUE THREAD

**Issue by mattague** [searxng/searxng#1646]
**Is your feature request related to a problem? Please describe.**
I would love if the hostname_replace feature allowed/supported replacing subdirectories as well

**Describe the solution you'd like**
The way hostname_replace currently works, it will not recognize subdirectories, so when I want to replace en.wikipedia.org with www.wikiwand.com, I am unable to because I have to replace the /wiki as well, and this is unsupported. I need to turn "https://en.wikipedia.org/wiki/<insert-item-here>" into "https://www.wikiwand.com/en/<insert-item-here>"

**Describe alternatives you've considered**
I tried doing this by including the subdirectory in the regex, but it doesnt get matched still, not sure why to be honest. I had also been using an extension for wikiwand, but something in SearXNG is blocking it, so when I click on the link, i get regular wikipedia, and then if I refresj the page I get a wikiwand result.

**Additional context**
I use wikiwand to get a more modern look on wikipedia. I read wikipedia ***A LOT***, like, almost too much. I spend a couple hours everyday reading wikipedia articles. Because of this I appreciate the better readablility offered by wikiwand as well as the improved navigation.

**Comment by ACodingGenie** [comment]
I would like to see this feature implemented as well. Just haven't made a request for it since you already have lots to worry about. My use case is with [Bibliogram](https://bibliogram.art/) which throws a 404 if `/u` is missing from the path, like in this case: `https://bibliogram.art/leomessi/`. With `/u` included, it works properly: `https://bibliogram.art/u/leomessi` (when not blocked by Instagram, of course).

Thank you!

**Comment by return42** [comment]
I close this feature request since the plugin its based on is outed .. lets discuss further in https://github.com/searxng/searxng/issues/3682
