### ISSUE TITLE
"!go" redirect gmail

### ISSUE THREAD

**Issue by SergioGlorias** [searxng/searxng#1748]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

```bash
$ git log -1
commit 691c0ed6b97c2480fdc1245fd09231b0b384bbf0 (HEAD -> master, origin/master, origin/HEAD)
Merge: 0d1af21f 66f72a00
Author: Alexandre Flament <alex@al-f.net>
Date:   Sun Sep 4 11:29:28 2022 +0200

    Merge pull request #1743 from dalf/update_about_metrics
    
    Update about the metrics

```

**How did you install SearXNG?**

using script https://docs.searxng.org/admin/installation-scripts.html

**What happened?**

**How To Reproduce**

use `!!go` to search google

**Expected behavior**

redirect to google

**Screenshots & Logs**

https://user-images.githubusercontent.com/9739913/188331867-50fa8c1f-27ce-4cb7-a782-75a218697f70.mp4

**Additional context**

**Comment by return42** [comment]
We use bangs from ddg https://duckduckgo.com/bang?q=!g

Use `!!g` for google and `!!go` routes to gmail:

![image](https://user-images.githubusercontent.com/554536/188383598-2a0967df-3ea6-4fb8-83f8-00ae9c52a4f4.png)

**Comment by dalf** [comment]
I think the underlying issue is the mismatch between the DDG bangs and SearXNG bangs.

If, for some reason, the user searches for `!go foobar` and wants to go directly to the website, `!!go` won't work as expected. In addition, the autocompletion doesn't provide a way to check the URL before sending the query.
So the only way is to open an additional browser window(or tab) and find the DDG bang on https://duckduckgo.com/bang

It could be better from the UX point of view.
For example, the autocompletion could display the target URL for `!!go`

**Comment by SergioGlorias** [comment]
So... when I use `!go` it googles it so I thought I just added more `!`

**Comment by return42** [comment]
> So... when I use `!go` it googles it so I thought I just added more `!`

This is an understandable thought .. I reopen this issue (label it with "new feature") and we have to think about how we can improve the UX ..

> It could be better from the UX point of view.
> For example, the autocompletion could display the target URL for `!!go`

Could improve the the UX but 

- https://github.com/searxng/searxng/issues/1566

will be a prerequisite.

I added this issue to chapter "Related" in issue

- https://github.com/searxng/searxng/issues/1604

**Comment by return42** [comment]
> So... when I use `!go` it googles it so I thought I just added more `!`

I close this issue in favorite of https://github.com/searxng/searxng/issues/2031#issuecomment-1361042800
