### ISSUE TITLE
Pagination is broken for Google Images engine

### ISSUE THREAD

**Issue by unixfox** [searxng/searxng#175]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
Commit number: `056550d523ddf4e06821957e13623fc322cf4675`

**How did you install Searx?**
Manually with `python -m searx.webapp`

**What happened?**
The Google Images engine doesn't have multiple pages, it only has one page. In contrary to Bing images which have multiple pages and the button "next page" is available.

**How To Reproduce**
1. `!goi test`
2. No "next page" button.

**Expected behavior**
Have multiple pages with "next page" button available.

**Screenshots & Logs**

<table>
<tr>
	<td>Google images
	<td>Bing images
<tr>
	<td><img src="https://user-images.githubusercontent.com/4016501/123101827-f425e480-d423-11eb-8735-462ef566fdb0.png" width="400">
	<td><img src="https://user-images.githubusercontent.com/4016501/123102259-64cd0100-d424-11eb-876f-780e9a0e383d.png" width="400">
</table>

**Additional context**

**Comment by return42** [comment]
@unixfox sorry for the delay .. I think we have to fix #183 first / see my https://github.com/searxng/searxng/issues/183#issuecomment-873611982 .. not so easy .. :-(

**Comment by return42** [comment]
Sorry I could not find a solution for paging support in google images.  I leave this open, may be others have a clever idea how we can solve the *infinite scrolling page problem*.

Google images is an infinite scrolling page and I do not have an idea [how to scrap infinite scrolling page](https://darmarit.org/searx/search?q=how%20to%20scrap%20infinite%20scrolling%20page%20%3Aen&categories=general&language=en).

I tried option [start](https://developers.google.com/custom-search/docs/xml_results#startsp) and [num](https://developers.google.com/custom-search/docs/xml_results#numsp) .. see diff below .. but google images seems to ignore both options 😞 

```diff
@@ -51,7 +51,7 @@ about = {
 
 # engine dependent config
 categories = ['images']
-paging = False
+paging = True
 use_locale_domain = True
 time_range_support = True
 safesearch = True
@@ -94,6 +94,8 @@ def scrap_img_by_id(script, data_id):
 def request(query, params):
     """Google-Video search request"""
 
+    offset = (params['pageno'] - 1) * 10
+
     lang_info = get_lang_info(
         # pylint: disable=undefined-variable
         params, supported_languages, language_aliases, False
@@ -107,7 +109,10 @@ def request(query, params):
         **lang_info['params'],
         'ie': "utf8",
         'oe': "utf8",
-        'num': 30,
+        # https://developers.google.com/custom-search/docs/xml_results#numsp
+        'num': 10,
+        # https://developers.google.com/custom-search/docs/xml_results#startsp
+        'start': offset,
     })
 
     if params['time_range'] in time_range_dict:
```

**Comment by kennedn** [comment]
Something to note that I have stumbled upon in tinkering with this issue myself; Passing certain User-Agent headers to google image results restores pagination support. I have been able to demonstrate this locally. Passing the User-Agent for a Kindle Fire HDX:

```bash
curl -X GET -H 'User-Agent: Mozilla/5.0 (Linux; U; en-us; KFAPWI Build/JDQ39) AppleWebKit/535.19 (KHTML, like Gecko) Silk/3.13 Safari/535.19 Silk-Accelerated=true' 'https://www.google.com/search?q=monkey&biw=320&bih=480&tbm=isch&ei=fs_1YMb7C5PXgQb525VA&start=20&sa=N'
```
Will then return a different set of images when the `start=` parameter is changed from 20 to 40:

```bash
curl -X GET -H 'User-Agent: Mozilla/5.0 (Linux; U; en-us; KFAPWI Build/JDQ39) AppleWebKit/535.19 (KHTML, like Gecko) Silk/3.13 Safari/535.19 Silk-Accelerated=true' 'https://www.google.com/search?q=monkey&biw=320&bih=480&tbm=isch&ei=fs_1YMb7C5PXgQb525VA&start=40&sa=N'
```

Neglecting to specify this User-Agent header seems to make google ignore the `start=` parameter.

**Comment by return42** [comment]
@kennedn thanks for sharing your experience ..

I can confirm; with the User-Agent from your examples, google-images returns to a paginated view.

I gave this solution a try and analysed google's response on this User-Agent ..

The paginated view (the HTML) differs completely from the HTML  _normal_ browsers will get.  If we want to parse this HTML response we have to reimplement the parser part of the gooogle-engine completely new.

I compared the HTML response with the parser we had before 16f8ec89 but the response for the User-Agent is not comparable with the old google-images parser we had before 16f8ec89 nor with the implementation we have today.

I still hesitate to (re-) implement the parser of the google-images because I do not know how long this "paginated view" will be returned by google ..

My experience is that _special responds_ depending on the User-Agent will disappear _sooner or later_ or are different in the different domains (google.com, google.fr, google.de ..). ATM I do not have much time to implement the new parser and run various tests to see how stable such a solution might be.  

If someone other has time to re-implement the parser part in the google-images engine, we are wiling to merge ... :-)

**Comment by kennedn** [comment]
Thanks @return42. I confirmed the same thing myself the other day in regards to the parser needing a refactor to make the user-agent method work. Something else that appears to be a deal breaker is that there's no way to retrieve full sized image urls from the response when using a malformed User-Agent. 

I have done a bit of a dig into the infinite scrolling problem itself though and have found that google now uses a "batchexecute" endpoint to get a batch of images periodically after a certain scroll threshold is hit. 

More images than are visible on screen are returned in any given batch and it appears some pixel values are sent along with this request (screen width and position from bottom). This hints that some server side calculations are going on to figure out how many images to send back in a given batch. The returned images can be controlled via a sequence number inserted into a couple of places in the request data. I've distilled this call down to the minimum required parameters and have had some success in manipulating the request data to get different sets of images in the response:

```bash
curl 'https://www.google.com/_/VisualFrontendUi/data/batchexecute' --data 'f.req=[[["HoAMBc","[null,null,[1,null,450,1,1440,[],[],[],null,null,null,545,100,[]],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[\"monkey\"],null,null,null,null,null,null,null,null,[\"\",\"\",\"\"],null,false]",null,"generic"]]]'

# HoAMBc - Magic value, always the same
# 1 - Sequence number
# 450 - ???
# 1 - ???
# 1440 - Screen width px
# 545 - distance from end of loaded images?
# 100 - Sequence number * 100
# monkey - Search term
```
You can vary the returned set of data by incrementing the sequence number and presumably could also tweak this by modifying the pixel values. It appears that all the required information could be plucked from the response if it were cleaned up and indeed may be a requirement going forward since additional images are added dynamically to the page from the data returned in this call, which breaks the current method of scraping the initial html for values.

I don't have a lot of free time right now to pursue this further so I thought I would share my findings as they are. I will however continue to tinker and am hoping to be able to get some sort of readable data out of a batchexecute response as a PoC.

**Comment by return42** [comment]
@kennedn thanks for pointing out _batchexecute_ / I already digging a into this API and I want to link here an article I found along others:

- [Deciphering Google’s mysterious ‘batchexecute’ system](https://kovatch.medium.com/deciphering-google-batchexecute-74991e4e446c)

**update**:  In a [branch](https://github.com/return42/searxng/tree/google-images-batchexecute) I am working on an implementation which uses _batchexecute_  / does not work yet / more investigation is needed.

**Comment by kennedn** [comment]
@return42 - I noticed that this was still open and decided to take another crack at deciphering the batchexecute protocol for image searches. I have managed to figure it out finally and have created a [reference script + step by step documentation](https://github.com/kennedn/google_batchexecute).

**Comment by Krando** [comment]
> @return42 - I noticed that this was still open and decided to take another crack at deciphering the batchexecute protocol for image searches. I have managed to figure it out finally and have created a [reference script + step by step documentation](https://github.com/kennedn/google_batchexecute).

Can anybody implement this solution in searxng? Is it possible?

**Comment by unixfox** [comment]
Issue fixed by implementing the new internal API explained in https://github.com/searxng/searxng/issues/1641
