### ISSUE TITLE
Bug: Chinese language header problem

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searxng#1822]
Version of SearXNG
I am using a public instance.

What happened?
It seems that most search results under search language zh-HK 🇭🇰 are from China (in Simplified Chinese and not specific to the Hong Kong region), whereas the results under zh-TW 🇹🇼 are actually more accurate for HK users.

Please note that this is not fixed by #1321, so I am reopening this issue.

How To Reproduce

For instance, to look up "https://www.price.com.hk/" with the search term "price+hk", the first result under zh-HK is a site from China, whereas the first result under Taiwan is (closer to) the correct result.

Expected behavior
Search result should be from Hong Kong region when search language is set to zh-HK

Screenshots & Logs
![173472663-c448f0f0-7162-41d1-8477-fd5edcd9d96b](https://user-images.githubusercontent.com/100532901/192936806-bf9898df-96f6-4cc4-ba40-929224e6673f.png)
![173472664-68875e60-15de-4a76-a70d-28b482f895e7](https://user-images.githubusercontent.com/100532901/192936809-696507c5-af26-4527-a1b6-ffeb9c698fd8.png)

Additional context
No sure if this is a SearXNG problem or that of the engines

**Comment by MarcAbonce** [comment]
Apparently, Google only supports `zh-CN` and `zh-TW` as seen in [our engines_languages.json](https://github.com/searxng/searxng/blob/master/searx/data/engines_languages.json#L810-L815) and in https://www.google.com/preferences#languages where only 中文 (简体) and 中文 (繁體) show up.

So when the user calls Google with `zh-HK` it will not find this locale and will instead match to `zh-CN`.

One way of solving this would be to manually match the Hong Kong locale to Taiwan. In `google.py` it would look like this:
```python
language_aliases = {
    'zh-HK': 'zh-TW'
}
```

The other, more complicated way, of doing this would be to add some logic to the `match_language` function, so that locales can also be matched by common script.

**Comment by return42** [comment]
Should be fixed by

- https://github.com/searxng/searxng/pull/2269

You can test it here: [!go :zh-HK price hk](https://darmarit.org/searx/search?q=%21go+%3Azh-HK+price%2Bhk)
