### ISSUE TITLE
[Bug] "Google" is missing a lot of results.

### ISSUE THREAD

**Issue by throwaway242685** [searxng/searxng#1829]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG.**

2022.09.29-a7d69323

**What happened?**

the Google engine is missing a lot of results.

this is **not** a duplicate of #1794. it's an entirely different issue that started to happen way before that.

**How To Reproduce:**

go to any [SearXNG](https://searx.space/) public instance, and search things like: `!go hl2 ost`, `!go tf2 ost`, `!go mgs ost`

you will get only 1 result.

but, if you go to any [Whoogle](https://github.com/benbusby/whoogle-search#public-instances) instance, and do the following searches: `hl2 ost`, `tf2 ost`, `mgs ost`

... you will get a lot more of results compared to SearXNG.

**Expected behavior.**

you should get more results by using `!go` in SearXNG.

**Screenshots & Logs.**

| ![screenshot_20221004-084731](https://user-images.githubusercontent.com/85243826/193813135-262aa82d-f119-47c3-aa51-fb14d4be0e78.png) | ![screenshot_20221004-084741](https://user-images.githubusercontent.com/85243826/193813190-0f1ca9b6-6cf3-4374-9b16-aa95b8af5b67.png) | ![screenshot_20221004-084749](https://user-images.githubusercontent.com/85243826/193813218-7e080c10-c676-4010-b530-425fd5a40865.png) |
| --- | --- | --- |

**Comment by MisterrrX** [comment]
I have also found that the longer your search query is, the less results will be pulled from Google. This doesn't happen when searching directly on Google.

**Comment by nameless326** [comment]
@dalf @return42 @mrpaulblack

**Comment by unixfox** [comment]
Compared to Whoogle, SearXNG selectively find the results based on [XPath](https://en.wikipedia.org/wiki/XPath) selectors which may exclude some results if Google creates new kind of results that may not be covered by our [XPath](https://en.wikipedia.org/wiki/XPath) selectors.

https://github.com/searxng/searxng/pull/1749 should fix this issue but it's blocked due to https://github.com/searxng/searxng/pull/1749#issuecomment-1261334691
