### ISSUE TITLE
Google images engine returning poorly sorted results with no simmilarity to google images or startpage images

### ISSUE THREAD

**Issue by ver4a** [searxng/searxng#1864]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Latest release on dockerhub, "2022.10.14-1a5b0965"

**How did you install SearXNG?**

searxng-docker

**What happened?**
With only google images enabled, image search returns oddly sorted results that, while funny, are quite useless.

**How To Reproduce**

- Enable only google images for image search
- Search for "first time meme"
- Do the same search on Google or Startpage and compare

**Expected behavior**

Results should be roughly the same as regular google images or startpage images.

**Screenshots & Logs**

Google images natively:
![image](https://user-images.githubusercontent.com/73035614/196078060-0161c8f8-d066-4d18-a5b5-5000fdde7f24.png)
Startpage images (just an example because they retain roughly the same order)
![image](https://user-images.githubusercontent.com/73035614/196078253-615f818c-3ea9-4a97-8659-85f67e9e8333.png)
SearXNG google images:
![image](https://user-images.githubusercontent.com/73035614/196078423-8073a057-1f5a-419a-9f2a-d6fb8bf16779.png)

**Additional context**

I am currently using qwant as a workaround and other image search engines work flawlessly too.

**Comment by dalf** [comment]
Perhaps related to https://github.com/searxng/searxng/pull/1792

**Comment by unixfox** [comment]
Is SearX hosted on the same IP address as the first google search that you did?

**Comment by ver4a** [comment]
Yes, it's hosted on the same public static IP I did the google search from.

**Comment by Shituation** [comment]
Take my friendly advice. Move on to other search engines. These people censores you.

**Comment by return42** [comment]
For reference / I addressed this issue in my rework of locales & languages: [`[mod] Google: reversed engineered & upgrade to data_type: traits_v1 `](https://github.com/return42/searxng/commits/master)

**Comment by unixfox** [comment]
> For reference / I addressed this issue in my rework of locales & languages: [`[mod] Google: reversed engineered & upgrade to data_type: traits_v1 `](https://github.com/return42/searxng/commits/master)

Can you explain a bit more what did you change for google images?

**Comment by return42** [comment]
> Can you explain a bit more what did you change for google images?

Everything :-) .. TLDR: this is only one commit of a series of commits with the aim of refactoring how locales & languages are handled in SearXNG.  In this task I developed a boilerplate to fetch properties (I call them traits since the word properties is already used in a different context).  On this bolierplate I refactored all engines that have "language" support, this includes (e.g.) all the google services (ddg, bing, startpage ...). Its a huge task I working on since 8 month or more.  When I re-engineered all the the request (and response) methods we had, I found a lot of issues e.g how a request (by example for google images) is done in SearXNG right now.  A fix of the request functions has not only an effect on the language/locale quality (what my first aim was) it also has its effect on the quality of results in general .. since the request functions are now much more elaborate there is also a reduced risk of getting captcha or having other issues.

My current developments (in the master branch of my github-fork https://github.com/return42/searxng/commits/master ) I test on https://darmarit.org/searx/ .. in parallel I continue to develop and fix bugs I find in practice.

So far I could improve a lot of things, the google engines are one of them ... it will take another 1-2 months until I am ready and want to present my developments here.

**Comment by dalf** [comment]
@unixfox https://github.com/return42/searxng/blob/302425023bbf424ce210a58ddef707ff55a914a8/searx/engines/google.py#L74

**Comment by return42** [comment]
Issue is fixed by:

- https://github.com/searxng/searxng/pull/2269

Not really 1:1 but the results should be improved.

**Comment by unixfox** [comment]
@return42 the google images engine is still using the google go API (https://play.google.com/store/apps/details?id=com.google.android.apps.searchlite&hl=fr&gl=US) which may give poorer results than the actual google images on www.google.com

**Comment by unixfox** [comment]
Sorry for the double message but for more context, the previous implementation would only give 1 page of results whereas with the google go API you can easily get as many pages as you want.

So there are drawbacks on both side, one may give poorer results but allow for pagination. While the normal google images give good results but only one page of results.

**Comment by return42** [comment]
> So there are drawbacks on both side, one may give poorer results but allow for pagination. While the normal google images give good results but only one page of results.

Thanks for your additional hints .. I left this issue open / may I have time at one day to dig deeper.

**Comment by dalf** [comment]
From the user point of view, does it make sense to use:
* the previous one page implementation for the first SearXNG page
* the current implementation for the following pages
?

**Comment by return42** [comment]
This was what come in my mind, but I need more reverse engineering to find a final solution.
