### ISSUE TITLE
Musixmatch request for "searxing" song lyrics

### ISSUE THREAD

**Issue by zstg** [searxng/searxng#193]
**Working URL to the engine**
https://www.musixmatch.com/search/%s

**Why do you want to add this engine?**
It can help get lyrics for songs (Google and Bing have these already but it doesn't seem to work on SearXNG

**Features of this engine**

**How can Searx fetch the information from this engine?**

Can be placed in the General category

**Comment by return42** [comment]
FYI today we add [AZLyrics.com](https://github.com/searxng/searxng/pull/287), you can test it at my instance by using `!lyrics ...` / e.g: [!lyrics don't worry be happy](https://darmarit.org/searx/search?q=%21lyrics%20don%27t%20worry%20be%20happy)

For me AZLyrics.com works much better than www.musixmatch.com and my experience is that  [www.azlyrics.com](https://www.azlyrics.com/) has a larger lyrics database compared to musixmatch.

If you think musixmatch should still be implemented for some reason, please argue / otherwise lets close this request .. thanks!
