### ISSUE TITLE
CryptoCheck.fr not using TLSv1.3 cipher

### ISSUE THREAD

**Issue by stephenhodgkiss** [searxng/searxng#1994]
**Is your feature request related to a problem? Please describe.**
After configuring SSL under Apache, I have achieved a rating of A+ according to SSL Labs. However, cryptocheck.fr is reporting a low E grade for the TLS checks.

**Describe the solution you'd like**
Consider moving to SSL Labs to get your TLS grades, as they are more up-to-date with the latest ciphers. CryptoCheck back in 2019 said that they could not offer TLSv1.3 support due to conflicts with how they developed their system.

**Describe alternatives you've considered**

**Additional context**

**Comment by return42** [comment]
Hi @stephenhodgkiss this is the project of the SearXNG server implementation.

Your topic is related to https://github.com/searxng/searx-space/ project, for any further discussion see:

- https://github.com/searxng/searx-space/issues/10
- https://github.com/searxng/searx-space/pull/35

.. I'm going to close this issue here.

**Comment by stephenhodgkiss** [comment]
My Apache2 SSL config now has:

SSLCipherSuite !DH:EECDH+AESGCM:EDH+AESGCM:AES256+EDH

This has resulted in A+ grades at cryptocheck.fr and also kept the A+ grade at SSL Labs. Thanks for your help, appreciated.

**Comment by return42** [comment]
@stephenhodgkiss thanks for your feedback :+1: .. in addition for those coming around while looking out for some help about Cypher-Suite (and cerbot) the following link might be helpful:

- https://github.com/searxng/searxng/discussions/1351
