### ISSUE TITLE
Users language selection should take precedence over autodetection

### ISSUE THREAD

**Issue by return42** [searxng/searxng#2018]
### requested feature

The core of SearXNG should provide the ability to distinguish between explicit language selection by the user and language suggestions from a plugin.

### background of the request

In PR-1969 we ..

- https://github.com/searxng/searxng/pull/1969

Autodetection of the language from the search term is a great feature often requested by our users.  It should become active by default but it is not enabled by default since it has one drawback --> **The autodetection takes precedence over user's selection and this can make SearXNG unusable for the user.**

----

copied from https://github.com/searxng/searxng/pull/1969#issuecomment-1345294431

SearXNG's locale of a query comes from (*highest wins*):

1. The ``Accept-Language`` header from user's HTTP client.
2. The user select a locale in the preferences.
3. The user select a locale from the menu in the query form (e.g. ``:zh-TW``)
4. Autodetection plugin is activated in the preferences and the locale (only the language code / none region code) comes from the fastText's language detection.

Conclusion: There is a conflict between the language selected by the user and the language from language detection of this plugin.  For example, the user explicitly selects the German locale via the search syntax to search for a term that is identified as an English term. 

Try ``:de-DE thermomix``, for example ..

In this screenshot the user selects the `de-DE` locale but the autodetect plugin has switched the language to `en` because the name of the product the user looks for is a English word

![grafik](https://user-images.githubusercontent.com/554536/206863668-815bea03-dbdc-437b-a872-cf7359b9eea0.png)

**Comment by ArtikusHG** [comment]
I see two ways how we could implement this:
- either make a change directly to the SearXNG source code, completely removing the plugin
- or, add a new boolean to the search class which shows whether autodetection should be done (e.g. autodetect language by default, but once a user has explicitly set the language by clicking on the languages dropdown menu, we only search in that language until they start a completely new search query)

I believe we should go the second way, but regardless of what we do first, I think the first thing to do is merge the PR in its current state, replace langdetect with fasttext, and only then make changes to the core SearXNG to make the plugin feasible for being enabled by default.

**Comment by return42** [comment]
> I see two ways how we could implement this:

My suggestion is to add a field (or two) to .. 

https://github.com/searxng/searxng/blob/abb33bd7ddf913fd98826584ed8b687889d3b346/searx/search/models.py#L29-L40

The fields are lists:

```python

   lang_suggestions = []
   locale_suggestions = []
```

But I haven't thought this to the end .. we can think about after PR is merged:

> I think the first thing to do is merge the PR i

I agree .. but give @dalf a last chance for review / I can't test the docker build chain.

**Comment by ArtikusHG** [comment]
> My suggestion is to add a field (or two) to ..

That is exactly what I wanted to do, just in a different manner. I don't think an array of lang_suggestions is needed, as we set fasttext to only detect one language, so I think a simple boolean like ```ignoreLid``` should be enough. It would be activated when the user selects a language manually.

**Comment by dalf** [comment]
See commit https://github.com/searxng/searxng/commit/f3c7ae6644c363d37291239a80b9c646bce2aab1 ([branch partial_fix_2018  in my fork](https://github.com/dalf/searxng/tree/partial_fix_2018)).

But it doesn't fix the issue: if the user choose "de-DE" in the form, the choice is going to be ignored.

The only way I see to fix the issue is to add include another value the language choices in addition to the existing special value "all". So it can be set in the settings, override in the preference, override in the form, and override in the query as usual.

![image](https://user-images.githubusercontent.com/1594191/208165097-07f2af3d-b23d-499c-aceb-2181a06999a4.png)

It does not make sense to let the user choose a language that is going to be override by the autodetection.
However if the user can pick "autodetect" as a language, it can be override as usual the form (drop down menu) or in text query (":de thermomix")

**Comment by ArtikusHG** [comment]
> if the user choose "de-DE" in the form, the choice is going to be ignored.

If I understood you correctly, I think this isn't very hard to fix - in the ```pre_search``` hook in the autodetect plugin we can add a check at the beginning that doesn't switch the language to the detected one if the query starts with : and a valid language/country code. If this is what you meant I can make a PR in your fork for this.

**Comment by dalf** [comment]
Scenario:
* autodetect is enabled
* the user sends a query
* the language is automatically set to `de`.
* then, the user would like to do the same query in English. Two paths:
  * first one: the user adds a `:en` to the query --> it will work as expected with a `pre_search` hook as you described.
  * second one: the user change the language is the form (the HTML element `<select>` for the language). How to detect that? The value can come from the result of the auto detection or be an user choice.

The way I see to solve this issue is to add a language named "auto" (similar to "all"):
* when a query is made, the "auto" value is replaced by the detected value
* the "auto" can come from settings.yml, the preferences, the HTML form, the query (`:auto`)

[EDIT] actually, not so sure.

**Comment by return42** [comment]
> The way I see to solve this issue is to add a language named "auto" (similar to "all"):

Instead of adding a new choice "auto":  

- If no language is selected by the (nor preferences setting, nor menu selection or syntax `de-DE`), the `Accept-Language` header from user's HTTP client is used.

- If user selects "all" (pref, menu) and the "autodetect language" plugin is active the language is set by autodetection. (this needs some modifications in the UI, not to change the lang "all" by what the plugin has been detected)

- If user selects language (different to "all", in the menu or in the preferences or by syntax `de-DE`) it takes precedence 

.. but I have a doubt /thinking loud:

What I miss in all this solutions is the region aspect 

--> quite often, users want to have hits that relate to their region 
--> The aspects of region and language can be very different (by example a Swiss wants french speaking hits in Switzerland `fr-CH`). 

---

EDIT: in a search engine like google users have two options:

1. don't set region nor lang in the preferences --> the search engine tries to determine what the user wants / to detect it has an internal algorithm that might be based on language detection from search term and a region from the `Accept-Language` header from user's HTTP client.  The algorithm is optimized on the search index the engine uses. 

2. Explicit selection of the region and language in the preferences (stored in a cookie)

**Comment by dalf** [comment]
> If no language is selected by the (nor preferences setting, nor menu selection or syntax de-DE), the Accept-Language header from user's HTTP client is used.

This is already the case: the default language is based on the HTTP header.

https://github.com/searxng/searxng/blob/b92748219504e67b18771b9831ffcebe76cca62f/searx/webapp.py#L540-L545

https://github.com/searxng/searxng/blob/b92748219504e67b18771b9831ffcebe76cca62f/searx/settings.yml#L32-L34

However, the purpose of auto detection is to use the text of query to define the search language

> If user selects language (different to "all", in the menu or in the preferences or by syntax de-DE) it takes precedence

* in the menu: without Javascript, how do you detect this is the choice of the user and not the detected language from the previous search?
* in the preferences: users won't understand why autodetection does not work
