### ISSUE TITLE
Bug: Brave has mismatch between links and descriptions due to advertisement

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#2020]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.12-966e9c3c

**How did you install SearXNG?**
script
**What happened?**
Results from Brave have mismatches between their URLs and their titles/descriptions

**How To Reproduce**
1. `!brave hatch act enforcement`
2. Look at results

**Expected behavior**
Results match titles/descriptions

**Screenshots & Logs**
![chrome_ClS315bTV8](https://user-images.githubusercontent.com/1284317/207478478-7d8a48a4-3b1d-4bef-af6a-4dba84bc7b72.png)

Note that the first result is an ad for a crypto wallet but the URL is to `osc.gov`. All the real results after are off by one.

**Comment by return42** [comment]
@allendema you are more familiar with brave than mine, do you see a chance to improve the XPath queries?

https://github.com/searxng/searxng/blame/9e9f57e48bb/searx/settings.yml#L1860-L1886

https://github.com/searxng/searxng/blob/9e9f57e48bbc3c07d49dad57bb851f59f1c7def8/searx/settings.yml#L1861-L1886

**Comment by allendema** [comment]
This issue is known.
Rn there are no ads displayed even when selecting :EN locale or doing multiple refreshes.

![searxng_brave_sorting](https://user-images.githubusercontent.com/64094914/207675733-9a4954b0-9f4c-4328-b5fe-63cc6582c9d3.png)

Can you @AlyoshaVasilieva do the same query on their site and copy the source-code to [a pastebin](https://bin.snopyta.org/)?

**Comment by AlyoshaVasilieva** [comment]
https://bin.snopyta.org/?34aa0efe209175a9=#Gi1hsAi7oHeKwQ9x7xXpvKKXf3GERBDFkzUdDfHkwhxy

Same search as my original report, the ad is now for `Ledger Nano X`. Redacted my geoloc info but it shouldn't affect anything else.

The search "Terra Vision" does not result in an ad on brave's site.

**Comment by allendema** [comment]
Give this a try: 
https://github.com/searxng/searxng/blob/9e9f57e48bbc3c07d49dad57bb851f59f1c7def8/searx/settings.yml#L1869

```    title_xpath: //*[@class="snippet fdb "]/*[@class="result-header"]/*[@class="snippet-title"]```

**Comment by AlyoshaVasilieva** [comment]
```
title_xpath: //*[@class="snippet fdb  "]/*[@class="result-header"]/*[@class="snippet-title"]
```

appears to work. Needs two spaces after `fdb`, GitHub collapses them into one if using inline code styling instead of triple backticks (weird decision on their part).

**Comment by return42** [comment]
@AlyoshaVasilieva @allendema thanks a lot for your suggestions / very helpfully .. I implemented PR https://github.com/searxng/searxng/pull/2178 .. would you like to test? / thanks :+1:

**Comment by return42** [comment]
For reference: https://github.com/searxng/searxng/pull/2178#issuecomment-1426650913

>  I think Brave needs to be a custom engine written in Python. 

This is also my impression, i think we need to delete the XPath implementation and wait until there is an implementation in python.

Update: sorry I pressed the close button.

**Comment by return42** [comment]
@AlyoshaVasilieva, @allendema IDK why, but I can't any longer reproduce this issue 

--> [!brave hatch act enforcement :en-US](https://darmarit.org/searx/search?q=%21brave+hatch+act+enforcement+%3Aen-US)

>  I think Brave needs to be a custom engine written in Python.

I opened an engine request ..

- https://github.com/searxng/searxng/issues/2294

for this / I'm going to close this issue, since we can't do more here.
