### ISSUE TITLE
Bug: bing sometimes missing first result

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [searxng/searxng#2068]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.12.30-647a0aa9

**How did you install SearXNG?**
script, also occurs in some public instances
**What happened?**
Bing is sometimes missing the first result.

**How To Reproduce**
`!bi pontiac aztek`

No Wikipedia article returned, 9 results are listed.

`!bi pontiac aztek wiki`

Multiple Wikipedia articles are returned, none of which are the English article for the Pontiac Aztek. (The Simple English and Scots articles appear.) 9 results are listed.

**Expected behavior**
The expected first result is the Wikipedia article for Pontiac Aztek. Bing.com returns 10 results on the first page, so SearXNG should return 10 results on its first page.

**Screenshots & Logs**
![SearXNG search](https://user-images.githubusercontent.com/1284317/210190306-e0f1bc25-9686-4ac4-8b31-8277c92b6d5b.png)
![Bing.com search](https://user-images.githubusercontent.com/1284317/210190309-83427d11-0893-4677-9ffd-93231b3e11a0.png)

**Additional context**
It seems consistent for specific search terms, but it doesn't always happen. My suspicion is that when the first result is fancy, such as a Wikipedia infobox, SearXNG doesn't see it.

**Comment by ahmad-alkadri** [comment]
Hello. I did some digging on this and I think I found out the reason.

The searx's bing engine seek the search results from bing that match the following xpath: `'//li[@class="b_algo"]'` as we can see in the following line of the `searx/engines/bing.py`:

https://github.com/searxng/searxng/blob/647a0aa98bd1d2000eb1ca5270e017d85d5c3463/searx/engines/bing.py#L87

Now, if we check the bing search results for the "pontiac aztek", we'll see that the Wikipedia result's element has a different class:

<img width="1532" alt="Screenshot 2023-01-03 at 08 14 13" src="https://user-images.githubusercontent.com/22837764/210314185-73e1a7ad-a6ee-4cac-945b-20d0de887cb9.png">

than the other normal results' element:

<img width="1532" alt="Screenshot 2023-01-03 at 08 14 50" src="https://user-images.githubusercontent.com/22837764/210314218-3731f090-05d7-483e-9308-07d3b88e4624.png">

I can modify the xpath for bing engine and then make a PR from it. Just need to make the xpath to be "every `<li>` element which has the class name containing `b_algo` (thus, the xpath will become `'//li[contains(@class, "b_algo")]'` instead of  `'//li[@class="b_algo"]'`) but I'm not sure if this is the correct step to take. Maybe the choice of using xpath `'//li[@class="b_algo"]'` is by design so that searxng will exclude the Wikipedia widget result. Can others give their input also on this? Thank you.

**Comment by return42** [comment]
> I can modify the xpath for bing engine and then make a PR from it. 

@ahmad-alkadri thanks for taking the time and digging into this issue .. would be great to receive your PR :+1:

**Comment by ahmad-alkadri** [comment]
> > I can modify the xpath for bing engine and then make a PR from it.
> 
> @ahmad-alkadri thanks for taking the time and digging into this issue .. would be great to receive your PR +1

@return42 Currently working on this; the xpath modification seemingly works well though now I need to find out how to remove this little part here 😅 

![screenshot-127 0 0 1_8888-2023 01 03-20_54_14](https://user-images.githubusercontent.com/22837764/210431786-a3805a50-be06-4dfc-8385-2e3f7d9ba43d.png)

Gonna keep trying things and once ready I'll push and make the PR.

**Comment by return42** [comment]
> now I need to find out how to remove this little part here 
> Gonna keep trying things and once ready I'll push and make the PR.

If you do not find a solution for the follow up issue, we can discuss it in a PR / send your PR as DRAFT is fine.

**Comment by ahmad-alkadri** [comment]
> > now I need to find out how to remove this little part here
> > Gonna keep trying things and once ready I'll push and make the PR.
> 
> If you do not find a solution for the follow up issue, we can discuss it in a PR / send your PR as DRAFT is fine.

@return42 Thank you. I managed to find the solution and I've made the PR. Please find it here: #2073. I'm available for any follow-up discussions on this.
