### ISSUE TITLE
OpenSearch not working

### ISSUE THREAD

**Issue by GGORG0** [searxng/searxng#2086]
When I right-click on the url bar it doesn't show "Add SearXNG" as an option - see below
![image](https://user-images.githubusercontent.com/51029895/211053698-8c04eefa-04e1-4c34-ad69-90c271db5186.png)

My instance is https://searx.ggorg.xyz/. 
In the devtools I see the meta tag being correct, also when I download the file ( https://searx.ggorg.xyz/opensearch.xml?method=GET&autocomplete= ) everything seems correct.
Also it works for literally every other SearXNG instance I visit

Edit: My browser is LibreWolf (Firefox) 108

**Comment by return42** [comment]
With a common FFox:

![image](https://user-images.githubusercontent.com/554536/211059137-c07125eb-b8b8-4577-bfaf-7dc50d102134.png)


UPDATE: May you have already added ? .. Check FFox search engine settings.

**Comment by GGORG0** [comment]
No, I don't have it aleady added. 
![image](https://user-images.githubusercontent.com/51029895/211061599-582239f0-a7c9-4acd-9def-48f26106b45f.png)

Also, when trying to add it using an "add custom search engine" extension it doesn't show up.
Literally every single other instance works, but not mine. This started like about a month ago, before it was working flawlessly

**Comment by return42** [comment]
Hmm, strange I don't have a clue .. from my site it works flawlessly .. what if you use a different browser or another device?

**Comment by GGORG0** [comment]
> Hmm, strange I don't have a clue .. from my site it works flawlessly .. what if you use a different browser or another device?

Well, on Firefox it works well too. Something is wrong with my browser because it only happens on this exact browser profile and on this exact instance.

**Comment by GGORG0** [comment]
Turns out that I just had to change the instance name to something other than "SearXNG" because LibreWolf has a SearXNG instance in browser policies and idk why that made it break

Maybe will be useful to other LibreWolf users which want to use an instance other than https://searx.be (the default one in LibreWolf)

**Comment by return42** [comment]
@GGORG0 thanks for pointing out: It seems to me that librewolf has preset the searx.be instance under the name "SearXNG".

- https://gitlab.com/librewolf-community/settings/-/blame/master/distribution/policies.json#L63

I see three drawbacks with this preset

1. The name of searx.be is "Searx Belgium" (not "SearXNG") --> 
2. since "SearXNG" is the name of most instances user will find on searx.space the majority can't be add to LibreWolf 
3. the preset is just a URL template ``"URLTemplate": "https://searx.be/?q={searchTerms}"`` that missed *autocompletion* (aka suggestions protocol) ``<Url type="application/x-suggestions+json" template="[suggestionURL]"/>``

- https://gitlab.com/librewolf-community/settings/-/issues/111#note_800684858
- https://github.com/searxng/searxng/issues/431#issue-1033790847

May we should open an issue at https://gitlab.com/librewolf-community/settings/-/issues and give the LibreWolf team some hints about?

**Comment by GGORG0** [comment]
> May we should open an issue at [gitlab.com/librewolf-community/settings/-/issues](https://gitlab.com/librewolf-community/settings/-/issues) and give the LibreWolf team some hints about?

Good idea, will definitely help other users

**Comment by GGORG0** [comment]
Another issue with LibreWolf: You should add a "May be required while using Firefox Containers or cache clearing" here:
![image](https://user-images.githubusercontent.com/51029895/211192522-f9f61df5-95ac-4446-9421-f475acf86815.png)
For example on LibreWolf when I use POST, I get this:
![image](https://user-images.githubusercontent.com/51029895/211192561-9d3ab011-0b85-4d29-801c-9f8469d94a46.png)
