### ISSUE TITLE
Disregard VPS locale

### ISSUE THREAD

**Issue by extremelyonline** [searxng/searxng#2141]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Latest Paulgo fork of SearXNG

**How did you install SearXNG?**
using searxng-docker

**What happened?**
I'm hosting SearXNG on a VPS. The VPS is located/has an ip from Japan. When visitors search "Amazon", the result is Amazon.co.jp, regardless of the language chosen by the user.

**How To Reproduce**
You can test it on the public instances hosted from a foreign country.

**Expected behavior**
The locale of the VPS should be disregarded.

**Screenshots & Logs**
/

**Additional context**
I am not sure if this is a problem with my own setup. I'm using Nginx and the real ip function has been tested.

**Comment by return42** [comment]
> I'm hosting SearXNG on a VPS. The VPS is located/has an ip from Japan. When visitors search "Amazon", the result is Amazon.co.jp, regardless of the language chosen by the user.

The locale handling has been improved by 

- https://github.com/searxng/searxng/pull/2269

By example my server is located in DE and if I search with engines that suppaort Japan language I get good results:

- [:ja amazon !bing !google](https://darmarit.org/searx/search?q=%3Aja+amazon+%21bing+%21google)

But we have also engines (activated by default) that do not support languages (or do not support Japan) .. compare:

- [:ja amazon](https://darmarit.org/searx/search?q=%3Aja+amazon)

In the latter query non Japan results from (e.g.) qwant or yahoo are mixed into the result list.  This issue can't be solved in general, it needs to be fixed in the engines itself.

It seems qwant does not support (see snippet below) Japan, and yahoo does return non Japan results.

Long story told short:  we can only improve engine by engine, please open issues for each engine where you think we can improve it.

https://github.com/searxng/searxng/blob/f950119ca87363aec81591dc4985f11371aa2b3e/searx/data/engine_traits.json#L3165-L3210
