### ISSUE TITLE
"We didn't find any results" in Bing

### ISSUE THREAD

**Issue by 9Ninety** [searxng/searxng#2301]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
darmarit.org, 2023.3.30+b1ea5b51

**What happened?**
It says no result available, works in about one or two week ago

**How To Reproduce**
Search with this link:
https://darmarit.org/searx/search?q=!bing+%22THN-3ME%22&language=auto

**Expected behavior**
Show what was available on Bing

**Screenshots & Logs**
**SearXNG:**
<img width="746" alt="Snipaste2" src="https://user-images.githubusercontent.com/38161479/229112676-99bcedc3-0c24-48bd-80ac-0aecbe954026.png">
**Bing:**
<img width="644" alt="Snipaste" src="https://user-images.githubusercontent.com/38161479/229112660-1441b49e-cd59-4cfd-b5f3-257c5aab22c2.png">

**Additional context**
**IP Address**: Japan
**Browser Accept-Language**: en-US, en

**Comment by return42** [comment]
> Search with this link:
> https://darmarit.org/searx/search?q=!bing+%22THN-3ME%22&language=auto

Don't use my server for bing queries / I'm sorry, but bing treats my server very bad --> you might remember our discussion in https://github.com/searxng/searxng/issues/2193

Other Instances do work better with bing, by example the one from

- @mrpaulblack : https://paulgo.io/search?q=%21bing%20%3Aauto%20%22THN-3ME%22 

Regardless of this, bing has always been problematic, there is always the problem that bing does not list any hits although the query should provide some.

I personally have disabled the bing, because it is constantly annoying with errors. 

There is certainly something that can be improved, when I have time I want to take a closer look ... but bing will always be a constant source of errors and glitches. :-(

**Comment by 9Ninety** [comment]
@return42 That's strange.. I discovered this on my own instance, then reproduced on your instance. I'll test again later to see what's going wrong.

**Comment by return42** [comment]
FWIW: [!bing :ja "THN-3ME"](https://darmarit.org/searx/search?q=%21bing+%3Aja+%22THN-3ME%22) does return results .. but not `:en`.  I suspect its related to what bing *thinks about my server's IP* .. With bing it seems to me that there is always a bit of magic or whoodoo.  I can not assess the behaviour of bing against my server, it behaves differently every few days.

> I'll test again later to see what's going wrong.

You can tell me about your experiences, I am a bit clueless with bing.

**Comment by 9Ninety** [comment]
| Site | Reproduced|
|-----|---------------|
|search.sapti.me|✅|
|search.rhscz.eu|✅|
|searx.fmac.xyz|✅|
|northboot.xyz|✅|
|search.ononoki.org|✅|
|searxng.nicfab.eu|✅|
|searx.be|✅|
|searx.work|✅|
|etsi.me|✅|
|freesearch.club|✅|
|search.bus-hit.me|✅|

**SearXNG received HTML**:
<img width="654" alt="Snipaste6" src="https://user-images.githubusercontent.com/38161479/229127277-5d463a57-fa38-44de-868e-fafb2f67dde9.png">

There must some magic on the Bing server 🤦‍♀️I can't reproduce this in my browser with same IP address.

**Comment by return42** [comment]
Maybe we need to adjust something in the bing engine in SearXNG to better emulate a "real" browser when requesting bing.

Unfortunately I don't have time for that at the moment ... let's see when I can do it.

**Comment by return42** [comment]
The error is currently not reproducible, all SearXNG instances listed above provide results for the query.  The search engine statistics of all instances give values of 100% or 90% for the reliability of the bing engine.

I close this issue.
