### ISSUE TITLE
[Feature] Shift/Ctrl Click a Category To Select Multiple Categories

### ISSUE THREAD

**Issue by Colburse** [searxng/searxng#2527]
Add the ability to shift/ctrl click another category to select it. This would work similar to how file selection works in GUI file managers (or just any kind of multi-selection functionality found in GUIs).
Clicking a category would deselect all other categories and search only for that category (similar to what the `Search on category select` plugin does).
Clicking a category while holding shift/ctrl would select that category and retain all the other selected categories (similar to the default behavior).

This would remove the need for the `Search on category select` plugin. Perhaps this request could be made into a new plugin which replaces it.

**Comment by Bnyro** [comment]
Since we're currently using buttons for the category selection (because there's no other way to do so with JavaScript disabled), I don't think we can implement this without any large refactor for now. The problem is that a feature like this requires JavaScript to be enabled, which would however likely break things for non-JS devices (if we don't add a separate third way for displaying categories that's handled via JavaScript, since at the time of templating at the server, the server has no knowledge whether the browser supports JavaScript).
