### ISSUE TITLE
"Add all engines" button

### ISSUE THREAD

**Issue by mareksagan** [searxng/searxng#2536]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An "Add all" button so I don't need to click a lot when I switch between Searxng instances.

**Describe alternatives you've considered**
None, it's already simple. Unless you want to add an "Add all engines" button for every search result type, it would be even nicer.

**Additional context**
Not much, it should just work.

**Comment by unixfox** [comment]
I think this functionality used to exist in the oscar theme.

**Comment by return42** [comment]
There are good reasons why some engines are inactive / activate all engines makes no sense.

**Comment by mareksagan** [comment]
Well, it makes sense to me, that's why I'm asking about it. Just saying "good reasons" doesn't seem like a sufficient explanation.

**Comment by return42** [comment]
> "good reasons" doesn't seem like a sufficient explanation.

Timeout by example ..

![image](https://github.com/searxng/searxng/assets/554536/da5f08a5-e1cc-45f7-a9df-c80fb9cbcd66)

and it makes by example no sense to search in archives for every query ..

![image](https://github.com/searxng/searxng/assets/554536/fa0942c3-a232-4622-b16b-ba0370916402)

These are just two reasons .. Simply turning on all the switches is an aimless approach:

The default configuration of an instance always pursues an intention, e.g. to supply the user the hits, which he looks for in general... and this in a waiting time as short as possible.

If the user has special searches, he can select specifically between categories or select single engines, e.g. via the search syntax.

The requirement to simply turn everything on seems inconsiderate in this context.

.. Close this request as not planned.

**Comment by unixfox** [comment]
It's just a small feature that I don't understand why it's not useful to be added?

Oscar has it and I sometimes like to use this option for testing all the engines or disable all the engines.

See 
![image](https://github.com/searxng/searxng/assets/4016501/d03ae1b3-e938-462d-9e09-5f260bfc96c4)

Can we reopen?

**Comment by return42** [comment]
The uninitiated user would always activate all engines, without understanding that he would only get disadvantages.  Even worse: certain engines are inactive, because you need them only for special searches and if you would always use them, the instances would be blocked.

Such an button is misleading in the intuitive user guidance and would also accelerate the degradation of the instance.

----

Related: https://github.com/searxng/searxng/pull/2519#issuecomment-1624825042

**Comment by unixfox** [comment]
But it's a power user option... a beginner is not going to touch this option. There are many other options for power users.

SearXNG users are mainly power users, let's not design interfaces only for "noob" people we are not Google nor Apple.

This option has been implemented in oscar for years and it has never been an issue.

**Comment by return42** [comment]
> a beginner is not going to touch this option.

I have my doubt.  We do not know how many users have saved this in a cookie .. and worry about "the slow response times". 

I am sorry, but I rate this option very doubtful.

> There are many other options for power users.

For power users we have the concept of *categories* (as tabs) and *groups* (e.g. `!lyrics`) 

--> https://docs.searxng.org/user/configured_engines.html

We can think about how to extend this concept even further, e.g. by configuring more groups.

**Comment by unixfox** [comment]
Rant: yet again a reason why I'm still using the oscar theme...

I really do not understand what's wrong in adding this simple feature that have not hurt anyone for years on searx with the oscar theme.

**Comment by return42** [comment]
> SearXNG users are mainly power users, let's not design interfaces only for "noob" people we are not Google nor Apple.

Using SearXNG should be as easy as using Google .. all users of my instance are "noobs" .. the intention of SearXNG is to provide a simple search engine to a broad public which -- unlike Google & Co -- protects the privacy.

-----

> I really do not understand what's wrong in adding this simple feature that have not hurt anyone for years on searx with the oscar theme.

As I wrote above: 

> Such an button is misleading in the intuitive user guidance ..

-----

> yet again a reason why I'm still using the oscar theme...

As I wrote above:

> We can think about how to extend this concept even further, e.g. by configuring more groups.

By example we could configure/implement something like a `!all` **group** that uses all engine in a category tab.   I haven't thought this through because I don't expect anything from it, but this would be a possible line of thought.

I still remain: a **button** (as requested here and implemented in oscar) that stores this setting in a cookie is the wrong approach.

**Comment by mareksagan** [comment]
Wrong? That's a strong word for just adding one feature... For me it makes the search engine harder to use when one instance is down and I need to quickly use another. If you want to attract more users, this is not really the way. You can do this through a group as long as it works (for me, it will be still a button/switch). The available instances don't have the Oscar theme, sadly (at least I don't see it) and it's a problem for me.

**Comment by return42** [comment]
To understand what I mean, please test it on searx.be 

1. Reset preferences to use searx.be defaults
1.a Type a query e.g. "foo" .. it will take about 2sec and you get a response.

2. In preferences activate all engines and save it.
2.a Do the same query again .. it will take about 7sec to get a response from searx.be and this result will look like this:

![image](https://github.com/searxng/searxng/assets/554536/dd4a342e-2ddc-42e3-943e-d892e1e7a8b2)

3. Select tab (category) "IT" .. it will take about 10sec to get this response ..

![image](https://github.com/searxng/searxng/assets/554536/416e9c90-05e7-4dcc-ac1a-bf5a1ab6e3b0)

Note the "Timeout" messages .. instead of 1-2sec to get response from searx.be you have to wait as long as the maximum timeout / on searx.be in category "IT" the maximum timeout is 10sec.

Since activation of all engines is saved in the cookie the user have to wait on the maximum timeout on every query .. 

In sense of user guidance this is in my opinion "wrong" / the common user would not notice that he waits about timeouts on every query. On the contrary, the user will come to the conclusion that the search engine is damned slow.

-----

Related: https://github.com/searxng/searxng/pull/2519#issuecomment-1624825042
