### ISSUE TITLE
"All engines" group/category

### ISSUE THREAD

**Issue by mareksagan** [searxng/searxng#2538]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An "All engines" group so I don't need to click a lot when I switch between Searxng instances.

**Describe alternatives you've considered**
None, it's already simple.

**Additional context**
Since there were some unexpected discussions and my previous issue was, for some reason, closed, I'm rephrasing the feature request and putting it here.

**Comment by return42** [comment]
> Since there were some unexpected discussions 

please take note of the reasoning https://github.com/searxng/searxng/issues/2536#issuecomment-1616143729, https://github.com/searxng/searxng/issues/2536#issuecomment-1616427438 / further related https://github.com/searxng/searxng/pull/2519#issuecomment-1624825042

> and my previous issue was, for some reason, closed

For those coming around and do not know what "previous issue" means, see discussion at #2536

> An "All engines"  group

I assume @mareksagan refers my comment:

[By example we could configure/implement something like a !all group that uses all engine in a category tab. I haven't thought this through because I don't expect anything from it, but this would be a possible line of thought.](https://github.com/searxng/searxng/issues/2536#issuecomment-1616150414)

----

A generic category like `!all` or `!all_in_tab` would not be stored in a cookie, unlike the suggestion from #2536 / the category would be specified via the search syntax if needed.

UPDATE:  There is already a group `!web` in the default config you can use.

**Comment by mareksagan** [comment]
I checked the !web group but it is not clickable so it does not solve my problem

**Comment by mareksagan** [comment]
@return42 I checked the **!web** group but it is not clickable so it does not solve my problem

**Comment by return42** [comment]
> but it is not clickable so it does not solve my problem

It's SearXNG search syntax / not sure what you expect .. a saveable preferences? .. this feature was already rejected in https://github.com/searxng/searxng/issues/2536#issuecomment-1616143729

**Comment by mareksagan** [comment]
Really? So what is the point of this ticket then? Just to tell me that you won't do anything?
