### ISSUE TITLE
[Engine request] Ecosia

### ISSUE THREAD

**Issue by RaptaG** [searxng/searxng#2556]
**Working URL to the engine**
https://ecosia.org

**Why do you want to add this engine?**
It is not included in the existing engines and the more searches you make, you contribute on planning trees

**Features of this engine**
Privacy friendly, contributes to the environment

**How can SearXNG fetch the information from this engine?**
Maybe there's something in https://github.com/ecosia

**Applicable category of this engine**
General

**Comment by unixfox** [comment]
Related: https://github.com/searx/searx/issues/2119

Useful comment:

> This was previously discussed in [#880](https://github.com/searx/searx/issues/880) and  [#1377](https://github.com/searx/searx/issues/1377).
The main problem is that searching Ecosia through searx would bypass their ads which is how they get the money to plant trees.

**Comment by blacklightpy** [comment]
Can't an exception be made for Ecosia? Do not strip private data on query and clicking results, or block ads for Ecosia. Also, Bing can be removed in favour of Ecosia. I think having this as an engine specific option would be nice, especially for this one. Or maybe it can be a special case to not clutter the UI, and the code changes can easily be applied for any other custom engines later on.

SearXNG is amazing, but for supporting Ecosia I'm not using it.

**Comment by unixfox** [comment]
> Can't an exception be made for Ecosia? Do not strip private data on query and clicking results, or block ads for Ecosia.

That's not possible, searxng is not a browser. It doesn't click on pages.

------

Closing due to https://github.com/searxng/searxng/issues/2556?notification_referrer_id=NT_kwDOAD1JdbI3MDk3NDc1ODIzOjQwMTY1MDE#issuecomment-1640415005

**Comment by dalf** [comment]
For information, on SearXNG `!!ecosia <something>` redirects to ecosia.com and here the ads can be seen.

**Comment by blacklightpy** [comment]
> That's not possible, searxng is not a browser. It doesn't click on pages.

@unixfox That's not what I meant. Doesn't searxng aggregates searches by querying the engines without sending private data? I also said clicks because searxng claims to remove data going to result pages.. maybe I should've said removal of trackers from result URLs (like referrer parameters). 

@dalf That's just bypassing searxng as a whole, not what I needed.

**Comment by unixfox** [comment]
We are not going to specially add back the trackers from ecosia just for this engine.

You said we remove the tracking data from the results given by ecosia, but that's because we ONLY retrieve the results given by ecosia that's it.

Anyway, this discussion leads to nowhere, we are not going back on our decision, there is no solution that doesn't involve hurting ecosia if we were to implement it into searxng.
