### ISSUE TITLE
[FEATURE REQUEST] language filtering and safe search with odysee

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#2706]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We can use, for example, language=de in the search URL. en, de-DE, and en-US also seem to work. There is no list of supported languages afaik, we just need to try things out one by one.

for safe search Moderate/Strict we should use nsfw=false in the URL

**Additional context**
The information that you need for this is here: https://github.com/searx/searx/issues/2504

----
Related

- https://github.com/searxng/searxng/pull/2656
- https://github.com/searxng/searxng/issues/590
- [lbr command line](https://gitlab.com/gardenappl/lbt/-/blob/main/lbt?ref_type=heads)
- [LBRY SDK ](https://github.com/lbryio/lbry-sdk/)

**Comment by Austin-Olacsi** [comment]
...looks like the supported languages where found here https://raw.githubusercontent.com/OdyseeTeam/odysee-frontend/master/ui/constants/supported_browser_languages.js

**Comment by Bnyro** [comment]
Unfortunately we can't really support safe search with Odysee: We can either
* set nsfw to true -> we only get nsfw results
* set nsfw to false (as currently due to defaults) -> we only get safe results

There's no way to get both, safe and unsafe results with one search request. We could make `nsfw` configurable by the engine host, but I'm not sure if it's a good idea. Imo, it's the best to just keep nsfw disabled and don't offer a config for it, so the search is always safe.
