### ISSUE TITLE
The magnifier button  always search in the general category.

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#2839]
**Version**

vanilla version 2023.9.22+75c9de02d

**How did you install SearXNG?**

Standalone docker image.

**How To Reproduce**

1. Search for something in the image category
2. Once the results are displayed, change the query
3. Press the magnifier to send a second query.

![image](https://github.com/searxng/searxng/assets/1594191/1bfd96e5-83da-4a38-83f9-06241e3726c9)

4. SearXNG returns result in the General category

**Expected behavior**

The magnifier should search in the selected category: in the above example it should search in the Images category.

**Comment by BernieHuang2008** [comment]
> 2. Once the results are displayed, change the query

the same query will also cause this.

I think the key is, we've got some `button` inside the `form`
![image](https://github.com/searxng/searxng/assets/88757735/e27ea7e0-cf69-4179-9a5d-a9d3cc80d945)
and button won't submit the data.

**Comment by return42** [comment]
Seems this issue exists since we merged:

- https://github.com/searxng/searxng/pull/2740

I try to understand what we missed in this PR:

- the magnifier glass is a submit `<button>` (before and after PR-2740)
- in the "category tabs", we switched from `<input>` to `<button>` 
- and when click on the magnifier glass (the submit button) the values from the "category tabs" are now longer send in the from of the new request (since these are now buttons).

I'm right so far?

If so, how could a fix look like? .. we have two use cases:

A. with "search on category select" enabled we have one active category
B. with "search on category select" enabled we have n active categories

I have seen #2389 / which adds a `name` attribute ..

```html
 {%- if search_on_category_select -%}
   name="category_{{ selected_categories[0]|replace(' ', '_') }}"
 {%- endif -%}
```

to the magnifier glass .. isn't it a bit hackish? / I assume this will only work for use-case A?

Isn't it better we additional add some (hidden) input fields back / like we had before PR-2740 was merged?

----

EDIT seems PR-2389 works for A and B .. TBH: I do not understand how it works.

**Comment by BernieHuang2008** [comment]
1. you're right so far.
2. this will only work for A. for caseB, it already works well.
3. i think not. if you add a hidden input, then submitting by other category button will also send it.
example:
add a hidden input `image` in the form.
-> case1: when submitting with magnifier ..... works expected.
-> case2: when submitting with another category-button (e.g. `video`) ...... the request will be `video & image` on.

**Comment by return42** [comment]
TBH: since #2740 I do not understand how the form works.
