### ISSUE TITLE
Uncaught TypeError: r is null

### ISSUE THREAD

**Issue by fluxth** [searxng/searxng#2921]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

48cb58bd2ec4eb9cb4ba416f7ece75c3c6c41e55

**How did you install SearXNG?**

Installed on AWS Lambda via https://github.com/fluxth/searxng-lambda

Though this bug also appear on other instances listed in searx.space

**What happened?**

<img width="551" alt="image" src="https://github.com/searxng/searxng/assets/9163891/d76b717a-94be-4907-be77-473f99d600d6">

`obj` is `null` here.

<img width="475" alt="image" src="https://github.com/searxng/searxng/assets/9163891/1078deb1-2ebc-4ecc-a7cd-66c8d8368caf">

**How To Reproduce**

Go to a searxng deployment (any server with recent version), and open browser dev console.

**Expected behavior**

There shouldn't be any uncaught JS exceptions.

**Screenshots & Logs**

Screenshot provided in previous section.

**Additional context**

See renovate PR: https://github.com/fluxth/searxng-lambda/pull/182

The first bad commit seems to be around commit 0ce1004, since the cypress tests start failing since that commit.
The last known good commit was 33496e7.

**Comment by return42** [comment]
I can confirm, this issue exists on the intro page.

On the intro page there are no Safe-Search or similar forms and the `d.getElementById('safesearch')` returns `null`:

https://github.com/searxng/searxng/blob/ff78b1a90265449495bc0200c6fa7706f4466468/searx/static/themes/simple/src/js/main/search.js#L153-L158

@Bnyro can you please have a look, this bug was introduce in a55e0ac553e in PR:

- https://github.com/searxng/searxng/pull/2740

**Comment by Bnyro** [comment]
I don't have much time this week unfortunately, I'll see if I can have a look in the weekend.
