### ISSUE TITLE
Engine request: MetaGer

### ISSUE THREAD

**Issue by Austin-Olacsi** [searxng/searxng#3005]
**Working URL to the engine**
https://metager.org

**Why do you want to add this engine?**
it's a great mix of results from yahoo, yandex and scopia.

**Features of this engine**
the source code of metager is on gitlab: 
https://gitlab.metager.de/open-source/MetaGer

**How can SearXNG fetch the information from this engine?**
possibly by scraping the html.

**Applicable category of this engine**
general

**Additional context**

**Comment by Austin-Olacsi** [comment]
Possibly useful: I've just found a search engine scraper written in python that supports metager (though i haven't tested it myself): https://github.com/tasos-py/Search-Engines-Scraper/blob/master/search_engines/engines/metager.py

**Comment by return42** [comment]
Related to MetaGer:

- https://github.com/searx/searx/issues/1427
- https://github.com/searx/searx/pull/2139
- https://github.com/searx/searx/pull/2538

**Comment by Austin-Olacsi** [comment]
seems that it's no longer a free service, they want you to pay them money to use metager now!
i am going to close this engine request.

**Comment by return42** [comment]
>  they want you to pay them money to use metager now!

Yeah, the story of MetaGer is a shame .. 

Back when Metager was launched in the 90s of the last century and was still operated at the University of Hanover as a service of the “Regional Computer Center for Lower Saxony”, Metager was an innovative project.  When the SUMA-EV association was founded, everything became complicated and bloated ... that was around 2004 and after that I had the impression that the quality was going down the drain.

In my opinion, the problem was that MetaGer did not focus on a community right from the start.  The association was only looking for funding and was busy building academic constructs ... The active level of doing, as we lively discuss and develop it here in the SearXNG community, unfortunately did never exists at MetaGer ... the publication of the sources (sometime around 2016) did not change anything and was just an attempt to revive a grilled chicken.  The intention was sacrificed to the temple of Mammon and at some point they were no longer afraid to hand over user data to third parties https://suma-ev.de/stellungnahme-microsoft-clarity/ 

It's a shame what the association has done with the MetaGer project.
