### ISSUE TITLE
Adding 'Day of week for date' as an instant answer feature

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#316]
**Is your feature request related to a problem? Please describe.**
No,it isn't related to a problem with SearXNG.

One can add a new instant answer returning the day of the week for an entered date .

**Describe the solution you'd like**

As I'm not quite sure on how to proceed, I seek help. I'd like help integrating **my** _Python_ package with searXNG's instant answers to return the day of the week a given date falls on.

**Additional context**
The Python package I made is available [here](https://pypi.org/project/DayOfWeek/) with the documentation/screenshots [here](https://github.com/Srinath-Anand/DayOfWeek#readme).

**Comment by return42** [comment]
> The Python package I made is available here

A link to the repository would be nice.

**Comment by ghost** [comment]
DayOfWeek on PyPI: https://pypi.org/project/DayOfWeek/

As such there's no GitHub repo, it's hosted only on PyPI.
Only the docs are hosted on GitHub.

**Comment by dalf** [comment]
I don't think DayOfWeek can be added because Python already has a function to do that.

But here some comments:
* there is no repository with the source code (WeekDay.py, setup.py, LICENSE).
* about the source code from the version 0.0.6 on https://pypi.org/ :
	* the source code makes a reference the MIT license without a copy of it.
	* it expects the date to be formatted in the format DD/MM/YYYY.
	* I'm not sure it handles [leap years](https://en.wikipedia.org/wiki/Leap_year). See the last paragraph of [Analysis section of the Zeller's congruence wikipedia page](https://en.wikipedia.org/wiki/Zeller%27s_congruence#Analysis).
	* the pattern `if Weekday == 1: print(...)` can be replaced by a dictionary `WeekdayText= { 0: "Monday, .... }`.
	* the usage `input` make it impossible to use in web server (there are only HTTP requests, no keyboard input).

About the Python implementation:
  * how to use it: https://stackoverflow.com/questions/9847213/how-do-i-get-the-day-of-week-given-a-date
  * Source code: https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/datetime.py#L88
	* it converts day, month, year values to an integer ( _ymd2ord function ).
	* the day of week is the modulo 7 of this integer.
	* you can have a look to the _ord2ymd function.

How to implement day of week in Python (not fully tested):
* create a searx/answerers/dayofweeks/answerer.py
* content:

```python
import datetime

from flask_babel import gettext

WEEKDAYTEXT = [
	'Monday',
	'Tuesday',
	'Wednesday',
	'Thursday',
	'Friday',
	'Saturday',
	'Sunday',
]

keywords = ('dayofweek')

def answer(query):
	parts = query.query.split()
	weekday = datetime.datetime.fromisoformat(date_str).weekday()
	return WEEKDAYTEXT[weekday]
	
		
# required answerer function
# returns information about the answerer
def self_info():
    return {'name': gettext('Date of week'),
            'description': gettext('Get the day of week'),
            'examples': ['date 1957-10-04']}
```
