### ISSUE TITLE
flake.nix

### ISSUE THREAD

**Issue by deviantsemicolon** [searxng/searxng#3238]
**Is your feature request related to a problem? Please describe.**
On NixOS, it is very difficult to maintain a package like searxng that doesn't have any fixed releases. SearxNG changes too often for  that to happen

**Describe the solution you'd like**
I want there to be a flake.nix file in the repository for NixOS users. Flakes are often used on NixOS for the purpose of having a git version of a package, and given the release model of searxng, I believe it would make sense to have a flake instead of a package. 

**Describe alternatives you've considered**
Again, the alternative is maintaining a package for it manually, which would have to have an outdated package report every time a commit is made

**Additional context**
A docker file can be used on Nix, but not in a way that's reproducible. NixOS modules for searx and searxng already exist, so the only thing needed would be a regularly maintained flake.nix file

**Comment by return42** [comment]
@jwijenbergh @SuperSandro2000 you are the NixOS experts .. what do you think about this request?

**Comment by SuperSandro2000** [comment]
> On NixOS, it is very difficult to maintain a package like searxng that doesn't have any fixed releases. SearxNG changes too often for that to happen

No, not really. Updates are just sometimes a bit delayed but with overlays it should be very easy to stay on the latest version. Also you could combine an overlay with a flake input to always get the latest an greatest.

If you want the newest version, you can always open a PR, tag me and it will probably be merged within a few days.

> I believe it would make sense to have a flake instead of a package.

We could do that but the package is probably not going anywhere, especially since I am a maintainer of it and I want to continue to use it.

> which would have to have an outdated package report every time a commit is made

Is that so bad? Not all of the changes are relevant for everyone and warrant that the package must be updated immediately. Especially dependabot commits are not relevant for us.

**Comment by jwijenbergh** [comment]
My two cents: I have a very hacky script that automatically updates the nix package every day. Seems to work great for my use cases. I don't think a nix flake is really necessary here
