### ISSUE TITLE
Bug: seekr_videos: page is sometimes broken

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#3284]
On the master branch, the paging for seekr videos is sometimes broken.

* `!seekr_videos berlin`
* go to the next page: same result
* go to the next page: different results
* go back page 2: different result from the first page

Search for `!seekr_videos berlin`, paging seems to work.

**Comment by return42** [comment]
The implementation to support paging is based on the nextpage method of Seekr’s REST API. This feature is next page driven and plays well with the [infinite_scroll](https://docs.searxng.org/admin/settings/settings_ui.html#settings-ui) setting in SearXNG [but it does not really fit into SearXNG’s UI to select a page by number.](https://docs.searxng.org/dev/engines/online/seekr.html#known-quirks)

----

Similar to 

- https://github.com/searxng/searxng/issues/3289#issuecomment-1980182112

**Comment by dalf** [comment]
So the engine remains broken?

**Comment by return42** [comment]
> So the engine remains broken?

Sorry for me it is not clear, what is broken?

----

When we switch to [infinite_scroll](https://docs.searxng.org/admin/settings/settings_ui.html#settings-ui) the *page support* works flawless

**Comment by dalf** [comment]
In other words, for this engine, the paging must be disabled without the infinite scroll.

**Comment by return42** [comment]
Not sure this is a good strategy .. in most use-cases users will jump from page 1 to page 2 and so on .. additional more and more *modern* image engines will have a *swipe* navigation  (e.g. [pintrest](https://github.com/searxng/searxng/issues/3289#issuecomment-1980182112)) .. do we want to show only the first page of results on all these engines just because we can't provide target-safe page navigation?

I see this quite pragmatically; nobody has noticed that the forward/backward navigation in pages does not work for these engines.  If we now deny users access to further images, these search engines would no longer be usable for users.

I would also like to see a better solution, but as long as this is not possible, the current solution seems to me to be the best compromise.
