### ISSUE TITLE
Bug: pinterest : error after paging multiple times

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#3289]
* search for `!pinterest time`,
* go to page 2
* go to page 3
* go to page 1 --> error

```
  File "/home/aflament/code/searxng/searx/engines/pinterest.py", line 54, in response
    'url': result['link'] or f"{base_url}/pin/{result['id']}/",
           ~~~~~~^^^^^^^^
KeyError: 'link'
```

**Comment by return42** [comment]
note:  on pinterest we can only scroll *forward* to the next page, there is no option to navigate to page X .. even we navigate *backward* in SearXNG UI, we select a *next page* 
 
https://github.com/searxng/searxng/blob/5602f0bf96866efdd73d39e686ef7413bc8caacb/searx/engines/pinterest.py#L41-L48

> go to page 1 --> error

the issue here was, that on page for new type of result types in the list .. we need to ignore them since they are not images:

https://github.com/searxng/searxng/blob/5602f0bf96866efdd73d39e686ef7413bc8caacb/searx/engines/pinterest.py#L52-L53
