### ISSUE TITLE
Google: Improve support for results with missing keywords

### ISSUE THREAD

**Issue by dsmith2001** [searxng/searxng#3484]
**Is your feature request related to a problem? Please describe.**

Yes, result descriptions that come from Google include the "Missing: [Keyword] | Show results with: [Keyword]" but there is currently no way to click on the option to show results with said keyword.

**Describe the solution you'd like**

- Show "Missing: [Keyword] | Show results with: [Keyword]" on a new line and make it more obvious it's a missing keyword and not part of the description
- Have the ability to click on the "Show results with: **[Keyword]**" to do what it says it does.

**Describe alternatives you've considered**

1. Remove the part with "Show results with: **[Keyword]**" and keep the "Missing: **[Keyword]**", putting it on a new line.
2. Remove the result entirely (not ideal, since the result may be still relevant)

**Additional context**
![image](https://github.com/searxng/searxng/assets/129474298/be2df41e-42ca-4b39-b557-2a5d57b6543e)

**Comment by Bnyro** [comment]
Thanks for the detailed issue :+1:

I decided to remove this kind of information from Google about missing keywords for now, because if we should implement something like `show results with: stats` which filters only results that contain the keyword, it should be done completely differently, integrated in SearXNG for all engines the same way, and not only for Google. Although I personally think that we don't really need something like that (anyways, that's something for an other issue if somebody is interested in that).

**Comment by virtadpt** [comment]
It would be handy to have, if only to simplify code that interacts with the SearxNG API.  As it is, search hits have to be filtered to ensure that they do have the search term in question but don't have "Missing: foo" in the search result or page linked to.
