### ISSUE TITLE
[help wanted] Flowise Integration

### ISSUE THREAD

**Issue by toi500** [searxng/searxng#3535]
**Describe the solution you'd like**
SearXNG would be a really good and powerful tool to have on Flowise.  Would it be possible to consider an integration?
https://github.com/FlowiseAI/Flowise/issues/2525

**Additional context**
Since SearXNG already integrates with JS LangChain as a tool, this integration might be relatively straightforward.

**Comment by return42** [comment]
Can you give us some more words .. personally I don't know about Flowise nor LangChain .. I read both are LLM tools .. OK .. but what is the task of SearXNG in the desired integration model.  Further, please understand that https://searx.space/ was made for humans, we will always protect these instances from automated access / BTW the instances there usually do not offer API access either.  The LLM players must set up their own instances (IPs).

**Comment by seonghobae** [comment]
I wrote https://github.com/FlowiseAI/Flowise/issues/2525 this, but I intend for dockerized personal searxng instances per integration of Flowise, not public instances. Because public instances are someone's network contribution, that may affect their real internet experiences. They will experience more captcha.

**Comment by toi500** [comment]
Exactly as @seonghobae said, the idea here is not to use it with public searx instances to prevent any sort of abuse but with self-hosted instances instead.

The general concept: https://python.langchain.com/v0.1/docs/integrations/providers/searx/

And here is how JS LangChain implements it:
https://js.langchain.com/v0.2/docs/integrations/tools/searxng/

**Comment by seonghobae** [comment]
I think this issue is inappropriate here: it’s already built on langchain.js framework. Nothing to do on the searxng side.

**Comment by toi500** [comment]
> I think this issue is inappropriate here: it’s already built on langchain.js framework. Nothing to do on the searxng side. 

It is not an issue but an integration request to the SearXRG team to help, if possible, with the https://github.com/FlowiseAI/Flowise/issues/2525#issue-2324741846 which was tagged as `Wanted Help` by Flowise devs.

If you have the technical knowledge to get this done without their help, please go ahead. I would be really happy to see this done.

**Comment by toi500** [comment]
> Can you give us some more words .. personally I don't know about Flowise nor LangChain .. I read both are LLM tools .. OK .. but what is the task of SearXNG in the desired integration model. Further, please understand that https://searx.space/ was made for humans, we will always protect these instances from automated access / BTW the instances there usually do not offer API access either. The LLM players must set up their own instances (IPs).

LangChain and Flowise are tools that allow developers to build applications based on LLMs. These tools enable the development of AI agents capable of utilizing various functionalities, in this case Searxng like a tool.

The use of this tool by an AI agent is similar to what a human does when setting up their own Searxng instance, to retrieve accurate information from the internet. There are many ways this can be helpful, in my personal case for using an AI agent for research. 

In any event, I have now closed this request, as I don't see a real interest in this community for this.

I'll try the implementation myself. While I'm not a JS expert, I'll let this community know if I succeed.

Thank you for your time and for your great work here. Loving it so far.

**Comment by return42** [comment]
> Because public instances are someone's network contribution, that may affect their real internet experiences. They will experience more captcha.

That was my topic / thanks for clarify :+1:

> The use of this tool by an AI agent is similar to what a human does when setting up their own Searxng instance, to retrieve accurate information from the internet. There are many ways this can be helpful, in my personal case for using an AI agent for research.

:+1: 

> In any event, I have now closed this request, as I don't see a real interest in this community for this.

Sorry if I left the wrong impression, I just didn't realize that you were asking for help / the title was tagged by ``[Feature]`` .. I set tag "help wanted". 

Unfortunately we don't have the resources to familiarize ourselves with flowise, but we are happy to answer questions about SearXNG so that you can integrate it optimally.

@seonghobae don't hesitate to ask your questions here .. and feel free to (ask for) reopen this issue.

**Comment by seonghobae** [comment]
Integrating Flowise into Searxng could help us improve the search logic of Searxng, but I don't think it would improve the value of the search itself. Instead, integrating Flowise would allow us to be a little more flexible with natural language search. I'm not sure how effective this would be, but think of it as a way to automatically evaluate and include appropriate search terms when a user types a question in natural language as a sentence. Maybe that's what this issue is about. It must have been an embarrassing issue for the Searxng community because there was too little context...
