### ISSUE TITLE
Installation issue with setuptools 71

### ISSUE THREAD

**Issue by ewilly** [searxng/searxng#3665]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
master / commit  ffde256

**How did you install SearXNG?**
using coman d suggest in dac with virtualenv

**What happened?**
`pip3 install -e .` failed with stout `error: metadata-generation-failed`

**How To Reproduce**
execute `pip3 install -U pip setuptools wheel pyyaml` and then `pip3 install -e .` 

**Workaround**
force setuptools < 71 by executing 
`pip3 install -U pip "setuptools<71.0.0" wheel pyyaml` instead of `pip3 install -U pip setuptools wheel pyyaml`

**Context**
see https://github.com/YunoHost-Apps/searxng_ynh/issues/304

**Comment by return42** [comment]
Install SearXNG into a python virtual environment ...

```
python -m venv myenv
. ./myenv/bin/activate
pip install -U pip
pip install -U setuptools
pip install -U wheel
pip install -U pyyaml
pip install .
```
> ... and then `pip3 install -e .`

If you want a developer install use the shortcut

    make install
 
the make will create a virtual env in `./local/py3` and does a developer install.

**Comment by ewilly** [comment]
Not sure to understand you response.
Installation of searxng is already a virtual env and works well until setuptools recently update from 70.3.0 to 71.0.3.
setuptools-71.0.3 (provide when executing `pip install -U setuptools`) is creating an issue
setuptools-70.3.0 is not creating an issue

**Comment by return42** [comment]
> Installation of searxng is already a virtual env 

:+1: 

SearXNG is not a common python package .. you can't install it into your systems's python .. you need to create a [venv](https://docs.python.org/3/library/venv.html)

> and works well until setuptools recently update from 70.3.0 to 71.0.3.

it works well with all setuptools that had been released in the last years .. but its recommend to upgrade setuptools in the venv / here is your venv:

https://github.com/YunoHost-Apps/searxng_ynh/blob/master/scripts/install#L28

and instead of downgrading setuptools:

https://github.com/YunoHost-Apps/searxng_ynh/blob/master/scripts/install#L30

you should update these packages:

```
pip install -U pip
pip install -U setuptools
pip install -U wheel
pip install -U pyyaml
```

The `error: metadata-generation-failed` comes from outdated build tools packages. I suspect the wheel from the OS does not fit to the updated setuptools .. it is recommended to update both packages in a line.

- [Install SearXNG & dependencies](https://docs.searxng.org/admin/installation-searxng.html#install-searxng-dependencies)
