### ISSUE TITLE
Safe search is set to strict ignoring settings.yaml

### ISSUE THREAD

**Issue by Immortality-IMT** [searxng/searxng#3731]
Verson: 2024.8.9+f1c05e7c1
Installed: via install script

The safe search is always set to strict disregarding the settings.yaml
Until a cookie is set with the preference.

Clear the cookie cache and restart uwsgi the safe search setting is set to strict 2 while in the settings.yaml it is set to 0.

The settings.yaml should provide the default setting.

Strangely, if I add a setting, say safe_search2 in settings.yaml and change preferences.py with settings['search']['safe_search2'] it grabs the value correctly otherwise it does not.

Adding print statements both in webapp.py and preferences.y logs the value 2 in both cases

preferences.py:479:        print(settings['search']['safe_search'])

**Comment by Immortality-IMT** [comment]
There is a second settings in /etc/searxng/settings.yml

When using... sudo systemctl restart uwsgi

It runs the sim link config /etc/uwsgi/apps-enabled/searxng.ini pointing to /etc/uwsgi/apps-available/searxng.ini

SearXNG configuration (settings.yml)
env = SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml

** Should there only be a single settings.yaml in /usr/local/searx/searxng-src/settings.yaml

if it's not required, having two settings.yaml causes confusion

I have changed line 25 in /etc/searxng/settings.yml to point to /usr/local
SearXNG configuration (settings.yml)
#env = SEARXNG_SETTINGS_PATH=//searxng/settings.yml
env = SEARXNG_SETTINGS_PATH=/usr/local/searxng/searxng-src/searx/settings.yml

and restart uswgi

Searxng fails to restart.

However, commenting out safe_search and possibly every other non-essential setting utilizes settings.yml in /usr/local for the setting.

This needs rectification.

Merging the files to one location are then symbolic link, one of them works only if you change the ultrasecretkey otherwise seaxng won't start

**Comment by return42** [comment]
> Installed: via install script

really script .. or docker?

> There is a second settings in /etc/searxng/settings.yml
..
> I have changed line 25 in /etc/searxng/settings.yml to point to /usr/local

:confused: 

> env = SEARXNG_SETTINGS_PATH=/usr/local/searxng/searxng-src/searx/settings.yml

This is docker .. 

It is not possible to understand what you are doing ... or what you want ... the settings all work, they are in use 100 times.

The default settings are in the software under /usr/local , in /etc are the customizations ... there are different options how a settings.yml can be set up under /etc, this is all described under https://docs.searxng.org/admin/settings/settings.html.

If you want to test something, you do not need to set up an instance, you can simply start a developer environment with `make run`, this is described at https://docs.searxng.org/dev/quickstart.html.

**Comment by return42** [comment]
Please forgive me if I express it in all clarity: You have been keeping me from reviewing the PRs and further development for quite some time, because I have to clarify your partly incomprehensible and other users misleading posts ...

Please don't ask any more questions here before you have read the documentation, if you can't find answers to your questions there, then we have a forum where you can discuss your topics with the community [#searxng:matrix.org](https://matrix.to/#/#searxng:matrix.org)

We appreciate your interest in SearXNG and your willingness to participate.  But please understand that here in the SearXNG core project we do not have the resources to respond individually to every single person or scenario.  If you continue to ignore these circumstances and flood this core project with requests of this kind, I will be forced to suspend your authorization for the SearXNG project for a transitional period / this is a very harsh measure that I would be very reluctant to take.

Thank you for your understanding.

**Comment by Immortality-IMT** [comment]
Installation Script is sudo -H ./utils/searxng.sh install all
on Line 17: SERVICE_HOME="/usr/local/searxng"

Two settings.yaml are generated, which is confusing. Changing the options in /usr/local/searxng/.../settings.yml does not change the values because the settings being used are in /etc/searxng/

Is that not a tad confusing?
Could there be only a single settings.yml in 1 location
and perhaps symlink the other ones?

**Comment by return42** [comment]
@Immortality-IMT You constantly ignore all well-intentioned advice / You are banned for 30 days
