### ISSUE TITLE
Preferences don't save if loaded by search URL

### ISSUE THREAD

**Issue by An-anonymous-coder** [searxng/searxng#3974]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.10.28+b176323e8

**How did you install SearXNG?**

N/A: I used this instance: https://search.sapti.me/

**What happened?**

When I made a search using the search URL, it loads my preferences fine. However, if I then use the search bar on the website to conduct another search, the preferences reset. 

**How To Reproduce**

1. Open https://search.sapti.me/
2. Go to "Preferences" on the top right
3. Change a setting.
The most noticeable one is `USER INTERFACE > Theme style > Black"
5. Click "Save" on the bottom right
6. Go to "Preferences" on the top right
7. Go to the "COOKIES" tab
8. Copy the URL below "Search URL of the currently saved preferences:"
9. Clear all cookies and site settings
10. Go to [Brave](https://brave.com/)'s settings
11. Go to "Search engine" on the left
12. Open the "Manage search engines and site search" setting
13. Click "Add"
14. Paste the search URL copied to your clipboard under the "URL with %s in place of query" section
15. Fill in the rest of the values as normal ("Name" and "Shortcut")
16. Click "Add"
17. Click the three dots next to your newly created search engine entry
18. Select "Make default"
19. Click on Brave's search bar
20. Make a search
The preferences load as normal
21. Click on SearXNG's search bar
22. Make a different search
The preferences reset

**Expected behavior**

The preferences should be saved in cookies and not reset when you make another search

**Screenshots & Logs**

I can provide these if needed

**Additional context**

When conducting a search, the preferences are present in the URL data, but not after conducting the second search.

**Comment by sohzm** [comment]
as i understand it, the `Search URL of the currently saved preferences:` isnt for saving the preferences, its just provides url with our currently saved preferences. 

so what needs to be done if you want the setting to persist is you gotta paste the `URL to restore your preferences in another browser:` to save the preferences then you can use the `Search URL of the currently saved preferences:` for search default.

imo there should be a way to do both together so that things like brave sync would work really well even on new device without running to the second url

**Comment by return42** [comment]
Close due to lack of feedback
