### ISSUE TITLE
only show green results not working properly

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#3978]
Added plugin only show green results

```
/usr/local/searxng/searxng-src$ sudo -H -u searxng -i
(searx-pyenv) searxng@toulibre:~$ pip install git+https://github.com/return42/tgwf-searx-plugins
Collecting git+https://github.com/return42/tgwf-searx-plugins
  Cloning https://github.com/return42/tgwf-searx-plugins to /tmp/pip-req-build-phi3mb7q
  Running command git clone --filter=blob:none --quiet https://github.com/return42/tgwf-searx-plugins /tmp/pip-req-build-phi3mb7q
  Resolved https://github.com/return42/tgwf-searx-plugins to commit 83d269e1b37661727646053d4c3d6bb042447b56
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tgwf-searx-plugins
  Building wheel for tgwf-searx-plugins (setup.py) ... done
  Created wheel for tgwf-searx-plugins: filename=tgwf_searx_plugins-0.4-py3-none-any.whl size=3178 sha256=ec7b5f20b057c068d34a247bb980d816dd51c2dc74d8521df91097fa2c3a9879
  Stored in directory: /tmp/pip-ephem-wheel-cache-6we6kvct/wheels/fb/84/a3/9de7525a49d0bae69a43292932aaa30e2e1739a45ca26a9f1f
Successfully built tgwf-searx-plugins
Installing collected packages: tgwf-searx-plugins
Successfully installed tgwf-searx-plugins-0.4
(searx-pyenv) searxng@toulibre:~$ exit
déconnexion
/usr/local/searxng/searxng-src$
```

then activated this plugin througth settings.yml

Ended up not showing only green results, I've checked some with green web foundation checker

Very slow search (think because it's with api)

**Questions**:

- How to make it really search only green results?
did I forgot to do something on the way ?

- How to make it search with the last database and not with api ?

**Comment by return42** [comment]
I can't recommend this plugin .. it hasn't been maintained since a very long time / seems GREEN WEB foundation does not have more interest since https://www.thegreenwebfoundation.org/news/searching-the-green-web-with-searx/ ..  they have an instance https://searx.thegreenwebfoundation.org/search .. but this instance hasn't been maintained since a very long time .. and yes, it slows down the SearXNG instance .. and the result list did no longer contain result usable for end users / e.g. a query like [`searxng github`](https://searx.thegreenwebfoundation.org/search?q=searxng+github) won't show you a link to this repository.

**Comment by ghost** [comment]
Thank you, may I request this as an internal plugin instead of external plugin ?
Or eventually by adding green web foundation as a search engine ?
