### ISSUE TITLE
Feature: Real-time search results as users type

### ISSUE THREAD

**Issue by realies** [searxng/searxng#4024]
**Is your feature request related to a problem? Please describe.**
Currently, users must complete their search query and press enter before seeing any results. This creates a delay in the search experience and doesn't provide immediate feedback as users refine their queries.

**Describe the solution you'd like**
Implement a configurable live search feature that:
- Begins searching as the user types (after a configurable delay/debounce)
- Shows results immediately when the user hits enter
- Includes an admin setting to enable/disable this feature
- Allows configuration of minimum characters before triggering search
- Provides option to set debounce timing to manage backend load

**Describe alternatives you've considered**
- Limiting live search to specific engines that can handle higher query volumes
- Implementing a progressive loading approach where only top results are shown initially

**Additional context**
This feature would significantly improve user experience by providing faster feedback, but should be configurable to allow administrators to balance responsiveness with server load based on their infrastructure capabilities.

Configuration options could include:
- Enable/disable live search
- Minimum characters before search triggers
- Debounce delay (ms)
- Maximum number of concurrent requests
- Which search engines to include in live results

**Comment by return42** [comment]
I cannot currently imagine how a real time request could be implemented in SearXNG to meet the expectations of the users ... without causing damage to the engines during operation.

> Debounce delay (ms)
> Maximum number of concurrent requests
> Which search engines to include in live results

SearXNG is an aggregator, even with engines that respond quickly, a time of 1-2sec is to be expected for the fastest engines, which would be detrimental to the UI of a real-time search.

The results of engines that do not respond within the “Debounce delay” are not displayed --> the real-time search would not (always) correspond to a classic search with request-search & response-results --> incomplete hit lists in the real-time search are of no use to users.

Engines like our DDG engine, for example, could forward the real-time requests to DDG, but since DDG itself does not support real-time search, DDG would evaluate these requests as bot requests and then block the IP of the SearXNG instance --> the engines would degrade very quickly and the quality of the entire SearXNG instance would suffer as a result.

Real-time solutions that I have seen so far are usually based on a session and JS requests to load the hit lists in real time.

SearXNG was developed to protect the privacy of users .. we have deliberately not implemented a session, as this could theoretically be used to track a user .. further, SearXNG can used without JS on the client, a feature that some users use .. and we don't want to break.

**Comment by unixfox** [comment]
Yeah that's a bad idea sorry.

**Comment by realies** [comment]
@return42, I guess a less sophisticated way, where a rendered HTML response is prefetched before the use hits enter and drawn as they do, could improve the responsiveness experience, given it does not trigger bot spam detection.

I think McMaster Carr's website make me think of this, over there, pages are prefetched as you hover on the buttons.

**Comment by return42** [comment]
> I think McMaster Carr's website make me think of this, over there, pages are prefetched as you hover on the buttons.

This is auto-completion with icons .. not a real-time result list.  The icons exists in this autocomplete since you are searching in a catalog of materials ..

SearXNG integrates search engines, which is a different activity than selecting parts in a (limited) catalog.

------

![grafik](https://github.com/user-attachments/assets/9cf72d8e-cdf0-4961-a3d2-23593e66b12a)

**Comment by realies** [comment]
> SearXNG integrates search engines, which is a different activity than selecting parts in a (limited) catalog.

I think you took this too literally. SearXNG can return its search engine results as the user types in their query.
