### ISSUE TITLE
[question] Search suggestions in Brave URL bar?

### ISSUE THREAD

**Issue by ACodingGenie** [searxng/searxng#489]
I have done some digging on SearX GitHub page and other places but I can't figure out how to get search suggestions to work in Brave's (Chromium-based browser) URL bar. I am using a local instance deployed via docker, and it is set as my primary (default) search engine in the browser. It does work with other search engines just not SearXNG or Whoogle. Tried searx.be also with no luck. Has anyone gotten them to work?

EDIT: They do with in Firefox.

**Comment by mrpaulblack** [comment]
I had the same problem that suggestions in the firefox address bar did not work with my SearXNG instance. For me the problem was the following:
* I was running my SearXNG instance with Suggestions (autcomplete) disabled
* I added the instance to my browser as search provider
* I enabled autocomplete in my browser, but this did not work, since I disabled autocomplete in my instance
* Than I enabled autocomplete (suggestions) in my instance -> but this would still not work in the address bar of my firefox

Turn out the fix was to delete the search engine in the browser and all cookies and cached stuff from my instance. I than enabled autocomplete first in my instance and than after that added it as a search provider to my browser. This fixed the issue for me...

(Let me know if that helps... the thing is:  the instance is added as search engine to the browser via `/opensearch.xml` and its added in the header of the html files. It is also defined there if autocomplete is enabled or not; updating the settings does not update the file tho as far as i know...)

Example opensearch in header from my instance:
```css
<link title="PaulGO" type="application/opensearchdescription+xml" rel="search" href="/opensearch.xml?method=POST&amp;autocomplete=google"/>
```

[EDIT] you can also try out https://searx.tiekoetter.com/ , https://darmarit.org/searx/ or https://paulgo.io to list a few different SearXNG instances

**Comment by ACodingGenie** [comment]
Thanks for the reply. I did try your suggestions and unfortunately nothing seems to work with Brave, however Firefox continues to work properly. I did notice while I `tail`'d the SearXNG logs that Brave does not even attempt to make an autocomplete request to the server at all. Whereas with Firefox I see the requests and the suggestions populating below the URL bar like they're supposed to. 

EDIT: I also tried changing the request type from POST to GET and it doesn't work either. I have tried deleting all cookies and cache, removing the search engine from the browser, turning on and off the autocomplete in both the browser and `settings.yml` and nothing helps.

**Comment by return42** [comment]
I installed brave today to see how I can help. It is the first time I use Brave browser, but for me, the auto completion in the URL does not work, whatever search engine I choose. Even if I use Brave (Search engine) or google, disable/enable option for auto completion ..  nothing works.  Could this be an issue of brave browser itself?

**Comment by ACodingGenie** [comment]
@return42 @MrPaulBlack Thanks for the troubleshooting guys. I ran into some old issue on Brave's GitHub and the problem seems to be adding the search engine manually which is what I was doing. You instead have to make sure this setting is turned on under "Search Engine":
![image](https://user-images.githubusercontent.com/68975831/141365963-022ebdf7-3fee-4f63-a3c4-20d469b18e24.png)

Then you may visit the SearXNG instance you want to add and it should auto-populate under "Manage Search Engines". Once you make that instance the default. Ensure this setting is on as well:
![image](https://user-images.githubusercontent.com/68975831/141366470-e045e6c7-9ead-4a90-86f8-287d9cc37853.png)

Search Suggestions in the URL bar should work as expected :) 
Applies to other Chromium based browsers as well I believe!

**Comment by Dunravin** [comment]
A bit late to the party but leaving this here for anyone else who needs a solution for Brave browser.

Assuming you have added your SearXNG instance to Brave's search engine list and made it default, click the three dots for the entry and edit it to:

`http://localhost/search?q=%s`

The key here is the `?q=` part. 

You should now be able to search from within the address bar. One caveat is it takes a few seconds to return results, much longer than using the search bar but for me personally living with that is easier than ridding myself of the address bar muscle memory.

**Comment by return42** [comment]
@Dunravin you are posting to an >4 years old issue .. please have a look at the about page of the SearXNG instance https://searxng.website/searxng/info/en/about and read "How do I set it as the default search engine?"
