### ISSUE TITLE
About caching of static files and maintaining headers upstream

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#544]
**Is your feature request related to a problem? Please describe.**
Right now we do not maintain any caching headers or anything like that in this repo. The result is that an instance can either be slow (since no resources get cached) or it breaks for existing users of an instance when the caching policy is to lax... (I was having those problems since I had a 1 year caching policy for all static files for whatever reason on my instance). The solution was to just use delete all site data (including cache for that instance) or to disable cache in dev tools and reload the site. This is not an ideal situation tho, since there can be multiple deploys a day atm and every time the site would break with lax cache or be slow, since at least a 304 gets returned (when there is a no-cache header).

**Describe the solution you'd like**
In my opinion this should not be the the task for every mainainer to figure out, but rather maintained upstream in the repo itself (adding the headers in this repo makes them work in searxng-docker and when installing through scripts). After some reading (https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#revved_resources and https://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/) I think we should use revved resources. Meaning we add maybe like 2 year public cahe header to all files in /static and every time we change a static file we change its filename (could be an arbitrary number... the number of the commit for example). So when a existing users comes back and uses the instance, they will always have a fast site through caching most resources and immediately get the changes if any static file changes (since the filename changed and its not in the cache of the browser anymore)... This way we have the best of both worlds... The versioning could be part of our build script for the themes... When a theme gets rebuild we could take the number of commits on master and add a 1 to it and use this number as the version number which gets added to the generated file, like so for example: `searxng.1234.min.css` the script could also change the filename in the base.html jinja2 template. Adding the headers to /static requests should be easy in webadapter.py and all the dynamic files can get a `no-cache` directive....

**Describe alternatives you've considered**
Use `no-cache` header so every time a endpoint gets loaded the browser makes requests if the file changed. If it did not the servers returns a `304` which also also quite fast... (since the simple theme also does not have a lot of static resources that get loaded anyway)

**Additional context**
We should also think about adding the feature policy header and csp header upstream. They should not be IMO part of settings.yml but rather hardcoded somewhere and a maintainer can disable or enable them with a setting in settings.yml (if  they want to do something custom they can just disable the headers and do their own ones with a reverse proxy for example...)

**Comment by mrpaulblack** [comment]
Related to: https://github.com/searxng/searxng/issues/140

**Comment by dalf** [comment]
For reference;: https://github.com/searx/searx/pull/2242

**Comment by mrpaulblack** [comment]
I would rather do it as filename in the path tho and not as a param... :+1:

**Comment by return42** [comment]
I lost the overview ... AFAIK caching is implemented since:

- https://github.com/searxng/searxng/pull/932

but there is an issue:

- https://github.com/searxng/searxng/issues/964

to have an interim workaround a fix has been merged:

- https://github.com/searxng/searxng/pull/995

Since there is  "something" merged to solve the request from this thread and there are other threads open about this topic:

- https://github.com/searxng/searxng/issues/140 
- https://github.com/searxng/searxng/issues/964

.. I am going to close this issue / @mrpaulblack feel free to reopen.

-----

[1] https://github.com/searxng/searxng/issues/964
[2] https://github.com/searxng/searxng/pull/932#issuecomment-1067039518
[3] https://github.com/searxng/searxng/pull/932/commits/55833364401ed72c30b3e85c16824a75de6b547a
[4] https://github.com/searxng/searxng/pull/932#issuecomment-1067216426
