### ISSUE TITLE
Search Engine bugs

### ISSUE THREAD

**Issue by arsg0etia** [searxng/searxng#595]
Hello there! i would like to report bugs

can you please fix these:

duden ( HTTP error ) https://www.duden.de

etools ( Suspended: access denied ) https://www.etools.ch

gigablast ( parsing error ) https://www.gigablast.com/

imdb ( HTTP error ) https://imdb.com/

duckduckgo ( unexpected crash ) https://lite.duckduckgo.com/lite

mojeek ( Suspended: access denied ) https://mojeek.com

wikidata ( unexpected crash ) https://wikidata.org

google ( unexpected crash ) https://google.com

version of searx
1.0.0-1265-b27e5b97
searx instance: https://searx.tiekoetter.com/
Thanks in advance!!!

**Comment by dalf** [comment]
A bug report for multiple engine is difficult to deal with: how to reproduce the bugs? When to close this issue?

Can you create one issue per engine and how to reproduce the bug?

Look at the engine tab of https://searx.space : there is a report per engine and per instance.

> gigablast ( parsing error )

Fixed in https://github.com/searxng/searxng/pull/587

> etools ( Suspended: access denied ) https://www.etools.ch
> mojeek ( Suspended: access denied ) https://mojeek.com

Looking the "engines" tab of searx.space, these two engines are blocked on most of the public instances

> wikidata ( unexpected crash ) https://wikidata.org
> duckduckgo ( unexpected crash ) https://lite.duckduckgo.com/lite

This is httpcore.WriteError exception: it requires some investigation. Perhaps the outgoing connection(s) from the instance is/are not reliable.
Two settings to try:
* `http2: false`
* `retries :`

see https://searxng.github.io/searxng/admin/engines/settings.html#outgoing
https://github.com/searxng/searxng/blob/5307fd841d11d0bead4ef07147b46e584b3b1fe4/searx/settings.yml#L615-L621

-->
```
  - name: google
    engine: google
    shortcut: go
    network:
        # either one, either both
        http2: False
        retries: 2
```

```

```

ping @tiekoetter

> google ( unexpected crash ) https://google.com

I see an h2.exceptions.ProtocolError exception: a workaround is to disable HTTP2

> imdb ( HTTP error ) https://imdb.com/

I don't see any error

> duden ( HTTP error ) https://www.duden.de/

**Comment by tiekoetter** [comment]
@dalf Thank you for showing me the google workaround. Google mostly works flawlessly now.

A little bit unrelated but the problems with google appeared about two days ago. Google began to answer DNS queries with IPs that were located in Romania (I would normally expect Germany or the Netherlands). This happened with both my own DNS resolver and Google's one.

**Comment by dalf** [comment]
>  Google began to answer DNS queries with IPs that were located in Romania

I don't have a clue about this.
More or less related to this subject: https://news.ycombinator.com/item?id=29199365

**Comment by return42** [comment]
> Can you create one issue per engine and how to reproduce the bug?
