### ISSUE TITLE
Bug: etools engine

### ISSUE THREAD

**Issue by hercut** [searxng/searxng#696]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 1.0.0

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
IP is blocked by a captcha ..

![grafik](https://user-images.githubusercontent.com/554536/148247128-9924a795-2159-45cf-90b7-28be63052cec.png)

**Comment by return42** [comment]
The [implementation of the etools](https://github.com/searxng/searxng/blob/master/searx/engines/etools.py) engine is poor.  No date-range support, no language support .. since etools is just a metasearch engine which uses engines we already have in SeaarXNG I vote to drop this engine entirely from the source tree.

Give me your thumbs-up/-down or leave a note ...
