### ISSUE TITLE
Use weboas.is as a theme

### ISSUE THREAD

**Issue by AkiraOtosaka** [searxng/searxng#727]
Is your feature request related to a problem? Please describe.

Let's be honest, Searx and searxng themes is not so great (at least for me) 

Describe the solution you'd like

I know sounds stupid but it's awesome if Weboasis's front end be used for Searxng
https://weboas.is/
the author died and Published the source code
https://mega.nz/file/oMliRaxC#Fb-7HAm4mn9HtdTCkMFZlalsIRfZTWFohn9bkqIV2dI
https://bayfiles.com/B72fi559x5/weboasis_zip
https://www.solidfiles.com/v/4YLKyzDxWLW4G
https://x0.at/u6lC.zip
(Unlicensed but he said "I’m a man of my word and will post the source code publicly. Maybe someone can continue my work.")
and it's sad to see https://weboas.is/ be gone
So I wonder if it would be added to searx 

Describe alternatives you've considered

If not the source code, at least the idea or clone of it

Additional context

https://weboas.is/forum/index.php?topic=5760.0

**Comment by return42** [comment]
Developing and maintaining a theme is not such easy as you might assume. There is not a simple way to pull over the theme from one project to another project. Most often you have to develop the theme from the ground up / It is not comparable with changing a jacket.

ATM the SearXNG team focuses on the _simple_ theme.  We are a very small team and we do not have the resources to develop another theme (may be sometime), but we are open for contributions.

I will close this issue since there is not a simple way to pull over the theme from weboasis.
