### ISSUE TITLE
[RTL Layout] Don't flip Music ♫ category icon

### ISSUE THREAD

**Issue by GreenLunar** [searxng/searxng#770]
Using CSS `transform: scaleX(-1);`
Sorry for not committing a PR, and I have no good excuse for not doing so.

**Comment by mrpaulblack** [comment]
All inlined icons are already flipped in RTL since the RTL PR.

Its done here: https://github.com/searxng/searxng/blob/0c036ae2941bb203769d28fe2e26cc7f0488c910/searx/static/themes/simple/src/less/style.less#L36

And the flip is defined here for RTL: https://github.com/searxng/searxng/blob/0c036ae2941bb203769d28fe2e26cc7f0488c910/searx/static/themes/simple/src/less/style-rtl.less#L65-L67

Closing; Feel free to reopen if you meant something else or you think this could be improved...

**Comment by GreenLunar** [comment]
Thanks. I've changed the subject.
Looking at the [screenshot](https://user-images.githubusercontent.com/1594191/149620444-ca2700e7-1f1f-4ecd-a7d3-88b77a28ff0f.png) of https://github.com/searxng/searxng/pull/750, we should make an _exception_ for the sign of ♫ Music category.

**Comment by return42** [comment]
@GreenLunar I fully understand your requirement, but to meet it would mean that we would have to consider each (possible) sign (symbol) separately.

This would make the implementation more complex and the effort in relation to the benefit is not justified compared to other requirements that are more urgent.

I ask for your understanding that we will not comply with this request and close the issue.

**Comment by GreenLunar** [comment]
Would you accept a pull request if I would send any?

**Comment by return42** [comment]
> Would you accept a pull request if I would send any?

Depends on the implementation. A PR is a concrete object on which to discuss.  Perhaps there is a simple implementation ...

**PRs are always welcome :+1:**
