### ISSUE TITLE
Tor over http proxy leads to internal server error

### ISSUE THREAD

**Issue by Dalethium** [searxng/searxng#790]
I know this is a really niche issue, however, I am using privoxy to proxy requests over an http proxy to tor OR a vpn depending on whether there is a .onion in the url. 

https://github.com/searxng/searxng/blob/96a1f79c6dcaa08a231ad3a28b8c17b677cddc9c/searx/network/network.py#L170

Effectively, I believe the issue lies in this check, if I enable tor networking in settings.yml the server gets an internal server error -- I believe this is because you manually check if the proxy is using remote dns prior to sending the actual request to tor instead of just asking tor if it's a tor IP. 

I am not sure if this needs fixing or not, as I am not sure if my use case is something you guys would want to account for, however, I believe it worth reporting.

**Comment by tiekoetter** [comment]
I have encountered the same issue. I fixed this in my fork of SearXNG. I could do a PR to fix the issue. But I am also not sure if this is an issue which needs to be fixed.

My SearXNG instance has this fix in place (reference: https://searx.tiekoetter.com/search?q=%21ah+test)

**Comment by return42** [comment]
@tiekoetter would you like to open a PR .. then we can discuss if there is a need and we can see what your fix is / thanks!

**Comment by dalf** [comment]
The two commits I have found:
* https://github.com/searxng/searxng/commit/6d3a1c88f6b8926a55a030215d4e9a4eb2cf90c2
  It requires in investigation: httpx internal code has changed recently.

* https://github.com/searxng/searxng/commit/b84acb7e8d5d0c0fcaf1dc751bb3195b3fd5d1c8
  the check should be done per network instead per engine.
  so it is possible:
  * to set `using_tor_proxy` in the default network
  * or per engine (since each engine has a network)

**Comment by tiekoetter** [comment]
I will create a specific branch later in the afternoon where I will do the commits more aligned with the guidelines and without the other changes I have made.
