### ISSUE TITLE
Simple theme: keyboard navigation / arrow keys support

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#836]
The keyboard navigation code is quiet complex and has issues:
* https://github.com/searxng/searxng/pull/689
* https://github.com/searxng/searxng/pull/812

I suggest to make a PR:
* to do some refactoring 
* not to rely on `.nextElementSibling`. Instead make a list of the `.result`. Find the current index position and go to the next index (even if the element is another `<div>`).

**Comment by mrpaulblack** [comment]
Just for tracking: the keyboard navigation in its current form is not fully working since the merge of the flexbox image PR. The PR introduced a image group when they are mixed with other results, which makes it not possible to go through every result with the keyboard navigation.

Also from https://github.com/searxng/searxng/issues/464 we should consider to support the arrow keys with keyboard navigation (right now its vim like key mapping)

**Comment by return42** [comment]
Has been fixed by:

- https://github.com/searxng/searxng/pull/916
- https://github.com/searxng/searxng/pull/2790
- https://github.com/searxng/searxng/pull/2724
- https://github.com/searxng/searxng/pull/2795
