### ISSUE TITLE
Search results pulled from google inaccurate

### ISSUE THREAD

**Issue by asianmusicguy** [searxng/searxng#886]
Search results pulled from google inaccurate searching for  some pulls horrible results 

![image](https://user-images.githubusercontent.com/39034611/153094845-47568f41-346e-44b7-a758-1e3cf3d9c118.png)

 

![image](https://user-images.githubusercontent.com/39034611/153095194-e73dba33-85ca-41d7-93df-f421aca627c0.png)

The first results should be pulled for such sites not outdated or odd links

**Comment by return42** [comment]
> Search results pulled from google inaccurate searching for some pulls horrible results
> The first results should be pulled for such sites not outdated or odd links

Sorry I do not understand what you asking for and the screenshot do not look bad to me. Can you please explain a little more precise what you expect and if you use your own instance or an public one (which?) / thanks.

FYI: we do filter out some adds from google resulta, this might confuse when you are looking for product advertising.

**Comment by unixfox** [comment]
I'm the one that asked @asianmusicguy to create an issue here because I can reproduce the issue too.

Basically, I don't really know why, but it seems like since the previous modifications of the XPath of Google engine the results are not great. I can reproduce the same issue with "English" as a default language.

Here is an obvious issue in the results given by Google, when I search for "telegraf centos" I don't find the official documentation on how to install the latest version of telegraf on centos.

On Google:
![image](https://user-images.githubusercontent.com/4016501/153153669-b487a36a-abe3-4c93-ada2-4d6acf390597.png)

On Searx.be:
![image](https://user-images.githubusercontent.com/4016501/153153737-4f1740be-e6cc-4a96-b3b6-1c6fd79a1e8c.png)

The URL I should have on the first results: https://docs.influxdata.com/telegraf/v1.21/introduction/installation/

I get the same bad results with these keywords too:
- `videojs Range header`: I don't get this link: github.com /videojs /video.js/issues/1968
- `royal tsx mosh`: I don't get this link: https://support.royalapps.com/support/discussions/topics/17000018892
