### ISSUE TITLE
Yandex engine request

### ISSUE THREAD

**Issue by TheFrenchGhosty** [searxng/searxng#961]
**Working URL to the engine**

https://yandex.ru/
https://yandex.eu/

(and more country specific TLD)

**Why do you want to add this engine?**

Yandex is the only big company backed search engine that isn't owned by a western company. 

It's the only one that doesn't filter anything (yes, this includes things about the current war) - Edit 2024-06-04: at least it hasn't be proven to be filtering stuff.

It's also only the only engine that doesn't "biases" its results for the sake of being politically correct/inclusive. (Example, I heard about recently: [DDG](https://duckduckgo.com/?q=blonde+braids&iax=images&ia=images) / [Yandex](https://yandex.eu/images/search?text=blonde%20braids)) - Edit 2024-06-04: some testing was done, Yandex.eu is now biased (though a lot less than DDG and western engines), the "problem" isn't present on Yandex.ru ([see here](https://yandex.ru/images/search?text=blonde%20braids)) (so both will have to be added)

**Features of this engine**

See previous points.

**How can SearXNG fetch the information from this engine?**

General, Images,Maps, Videos

**Additional context**

Support for it was removed in #709 (but it basically was broken at this point)

**Comment by dalf** [comment]
Yandex engine was removed one year ago from searx because it returns CAPTCHA for any requests: https://github.com/searx/searx/pull/2566

I'm not sure the situation has changed.

**Comment by unixfox** [comment]
It still does and it's more aggressive since the start of the "war"

Issue safe to close.

**Comment by ghost** [comment]
> It still does and it's more aggressive since the start of the "war"
> 
> Issue safe to close.

Sad since this search engine is useful on some very specific search.

**Comment by nakoo** [comment]
Yeah, despite of current situation, yandex is really good search engine to find copyrighted contents.

**Comment by dmigis** [comment]
After reading issues about bot-sensitive engines like Yandex, I was thinking about partial solution for this problem (yup, it has tons of drawbacks, but still): why not to use Selenium/Puppeteer and Chrome/Firefox Headless as tools for retrieving of HTML-content of search result page? From my experience, I could bypass CAPTCHA and bans by using russian proxy and Chrome Headless configured for stealth operations.
Potential drawbacks:
1) Code complexity
2) Resource-consuming. (1 user - one chrome instance)
3) In case of public instances, multiple requests from 1 IP will lead to CAPTCHA anyway, so it will require pool of proxies or subscription to mobile proxy service (also to be integrated to SearxNG at least as a plugin).

So I have a question: if I manage to implement for example Yandex support via selenium, does this feature have a chance to be merged into the project? I'm willing to experiment on this topic, just willing to know, if my efforts wont go into the drain in case of decline of merging PR with selenium support. Thanks in beforehand.

**Comment by unixfox** [comment]
Unfortunately no we don't plan to implement a full browser into the project. But for your personal usage you are free to create a proxy that do the request from a full browser like I did in one of my project: https://github.com/unixfox/pupflare

**Comment by rohitrsm83** [comment]
Hi. Iam just a laymen; don't understand coding, development etc. Very happy with SearX but noticed the issue pertaining to Yandex. Was given to understand that I must present my suggestion here.

So while the Captcha issue is real,  I noticed that if you do an image search directly (like one can add the Yandex Image search engine as an option—among others—in Firefox search bar, and directly search for images), then it doesn't throw up a captcha and shows the results.

Perhaps, for now, only the Yandex image search can be added/enabled for the SearxNG image search function..? 

Thx.

**Comment by marclp** [comment]
I'd really like to see Yandex running in SearXNG, there is a [new XML api](https://yandex.com/dev/xml/) to access the search results, with no captcha walls; although in order to be able to use decent limits you need to register with an account and verify your phone number.

**Comment by unixfox** [comment]
> I'd really like to see Yandex running in SearXNG, there is a [new XML api](https://yandex.com/dev/xml/) to access the search results, with no captcha walls; although in order to be able to use decent limits you need to register with an account and verify your phone number.

Please see https://github.com/searx/searx/issues/3210

**Comment by whiteonion** [comment]
> I'd really like to see Yandex running in SearXNG, there is a [new XML api](https://yandex.com/dev/xml/) to access the search results, with no captcha walls; although in order to be able to use decent limits you need to register with an account and verify your phone number.

I am interested in contributing code to this extension. Do you want to collaborate on it?
 
> Please see [searx/searx#3210](https://github.com/searx/searx/issues/3210)

This is regarding SearX not SearXNG. Besides SIM verification can be done with prepaid SIM cards that are as private as possible.


Anyone wants to join? I’d appreciate not doing it alone… ?

**Comment by thunder-coding** [comment]
Here are a few interesting observations I just noticed:

- Only the Russian version yandex.ru is heavily asking for captcha verification (NOTE: this maybe due to my location being outside Russia)
yandex.com is not asking for captcha verification as aggressively as yandex.ru, whereas any sort of request to yandex.ru is always asking for captcha. Even trying to open the homepage is asking for captcha for yandex.ru, whereas on yandex.com I am able to search for stuff as well as open the homepage pretty easily.

- Searching directly using the search syntax triggers captchas
`https://yandex.com/search?term=<query>` always triggers a captcha, whereas opening the homepage and then searching works fine, even when doing a lot of queries in a short duration each opening the homepage in a new tab, always works fine. I have JavaScript disabled using NoScript so, this means that it should be pretty easy for us to scrap the tracking ids which the plain html comes up with and include that in the actual search to not trigger any captchas.

- Using the same search session multiple times triggers captchas
Opening the homepage and searching once never gives a captcha, but reusing the same session to do another search has a high probability of giving you a captcha

I have also recorded a screen recording of these observations but the video is too large to upload here. Will try to compress and upload here later

**Comment by MorsMortium** [comment]
It seems yandex does not use captchas that aggressively anymore. Could this be reopened?

**Comment by return42** [comment]
> I would prefer to implement the actual interesting engines in searxng instead of using another service for that.

If this true, we should rethink about yandex, but before a short summary of what we have had so far:

- Yandex was added 9 years ago: fafc56487
- and removed three years ago 5d9db6c2f
- Yandex has been added as autocompleter https://github.com/searxng/searxng/pull/1757
- a new attempt in 
  - https://github.com/searxng/searxng/pull/3201
  - https://github.com/searxng/searxng/pull/3733
- we have a yandex_music engine (IDK the state), added in 3c42252c https://github.com/searxng/searxng/pull/3234

Context:

- [yandex.com is not asking for captcha verification as aggressively as yandex.ru,](https://github.com/searxng/searxng/issues/961#issuecomment-1793728114)

Should we perhaps reopen draft #3201 ... or if the situation has changed fundamentally, should we perhaps strive for a completely different / new implementation?

-----

BTW It would nice to have the remote image search of yandex in SearXNG / see "Alternatives": https://github.com/searxng/searxng/pull/475

**Comment by TheFrenchGhosty** [comment]
Some information: 

Some testing was done (via the "Privacy Frontends - Offtopic" Matrix room), Yandex.eu is now biased (though a lot less than DDG and western engines), the "problem" isn't present on Yandex.ru ([see here for the blond braid example](https://yandex.ru/images/search?text=blonde%20braids)) - so both will have to be added.

I edited the original post of this issue.

**Comment by Aadniz** [comment]
It was already discussed in the matrix server, but I might want to add you can workaround the captcha issue by grabbing the content from eTools.ch. Of course, it's just putting load elsewhere and might just be about time before they also prompt for captcha (as discussed here https://github.com/searxng/searxng/pull/709).

Nevertheless, I made an implementation that works https://github.com/Aadniz/searxng/blob/yandex-fix/searx/engines/yandex.py but aren't writing a pull request as the stance I see on this problem is just making it more complex.

**Comment by ballo** [comment]
Yandex support would be great. So many search engines have been tinkered with to death (especially Google) and have become absolutely useless. If you actually know a specific string to search, Yandex is one of the few engines left which can do literals.

**Comment by vgdh** [comment]
Please add this search engine, it works great for that region.

**Comment by return42** [comment]
Yandex engines have been added a long time ago .. but set to inactive in settings.yml because of CAPTCHA  / see https://github.com/searxng/searxng/pull/3733#issuecomment-2587137905

https://github.com/searxng/searxng/blob/93751b63798bc9331987cef0e2dff17123a55325/searx/settings.yml#L2070-L2091
